### ISSUE TITLE
Put summary comments on contracts properties

### ISSUE THREAD

**Issue by Uriil** [Uriil/MetaTrader4.Manager.Wrapper#1]

**Comment by dnathemaster** [comment]
Really thanks for sharing this project.
but my code return an exception, here is my code:
ClrWrapper wrapper = new ClrWrapper("dll path");
Contracts.UserRecord ur;
ur=Wrapper.UserRecordGet(1);

Then i get a MetatraderException error.（other function works fine, like chart,trade transcation & etc.)
My idea is getting an user info with given login-id. please help me out, thanks.

**Comment by Uriil** [comment]
Hi, methods ending with get requires pumping mode.  Switch to pumping, or use UserRecordsRequest

**Comment by dnathemaster** [comment]
Thanks, i'll give a try.

**Comment by dnathemaster** [comment]
Hi Uriil, why did I get a userlist with nothing in it. 

Code:
            IList<int> id=new List<int>{1,3};
            IList<Contracts.UserRecord> ur;
            ur = wrapper.UserRecordsRequest(id);

run with no error, but i got an empty userlist :(

**Comment by Uriil** [comment]
Thats was a bug. Fixed it.

**Comment by dnathemaster** [comment]
works now :+1:

**Comment by dnathemaster** [comment]
Hi, 
Could u please show me how to get a symbolinfo with a given symbol(like USDCAD)?
Cause I want to get its price or digits.
I've tried using pumping swich with a callback, but I do not know how to get symbolinfo in the callback function. Please help me out :). 
Thanks again man.

**Comment by Uriil** [comment]
Using pumping:

using (var mt = new ClrWrapper(new ConnectionParameters { Login = 0, Password = "", Server = "" }, @"mtmanapi.dll"))
            {
               mt.SymbolsRefresh();
                //without pumping, but depends on MT server settings
                var r = mt.TicksRequest(new TickRequest() {Symbol = "EURUSD", From = 0, To = int.MaxValue, Flags = (char) 3});
                Assert.IsNotNull(r);
                
                var p = mt.PumpingSwitch((delegate(int i)
                {
                    //wait until 0 recieved, thats mean pumping started, and after 
                    //you will be able to recieve new quotes and access them
                }));
                Assert.AreEqual(0, p);
                mt.SymbolAdd("EURUSD");
                Thread.Sleep(30000);
                var symbol = mt.SymbolInfoGet("EURUSD");
                Assert.IsNotNull(symbol);
            }

**Comment by dnathemaster** [comment]
probably bug: (I wanna get symbol's config info like stops_level, profit_mode, contract_size)
IList<Contracts.Configuration.Symbol> si = null;
si == wrapper.CfgRequestSymbol;
(Run with error: Exception: System.NullReferenceException)
works fine for other CfgRequests like CfgRequestFeeder, CfgRequestFeeder & etc.

**Comment by Uriil** [comment]
Unfortunately I don't have admin access to MT server now(which is required for this method call), so I can't debug it. But if you could it woulb be great

**Comment by dnathemaster** [comment]
I can't debug the C++ part cause i'm not familiar with C at all, which is the error source :(
I would like provide you an MT admin for debugging if that's okay with you.
may i have your IM or Email? my MSN:around#live.com

**Comment by Uriil** [comment]
skype: uriil1987

**Comment by hoangtxss** [comment]
I am using MetaTrader4.Manager.Wrapper to connect to metatrader4
when i Login
it return 65
i know that is Invalid Error code
but i sure login info is correct
could you help me to solve this problem?

**Comment by dnathemaster** [comment]
code 65 is a wrong login info
