### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by lratjens** [Uriil/MetaTrader4.Manager.Wrapper#10]
Calling ReportsRequest and DailyReportsRequest

Recieving following error:

An unhandled exception of type 'System.NullReferenceException' occurred in P23.MetaTrader4.Manager.ClrWrapper.dll

Additional information: Object reference not set to an instance of an object.

Have spent quitesome time debugging and have hadsome external developers review. All indications are that there might be an issue with the wrapper. 

There is also a difference between the version number as per install and as per properties.

**Comment by Uriil** [comment]
I think I did not push latest version to nuget.
I will check these methods during weekend and let you know

**Comment by lratjens** [comment]
Thanks for the quick response! Let me know if you'd like any additional details / screenshots.

**Comment by Uriil** [comment]
Just checked.

Old version works. Could you please share with  code, which throws this exception?

**Comment by lratjens** [comment]
public static IList<DailyReport> GetMetrics(ClrWrapper mt, DateTime fromDate, DateTime toDate)
{
            var logins = new List<int>();
            logins.Add(2482);
            using (mt)
            {
                DailyGroupRequest request = new DailyGroupRequest();
                request.From = (uint)fromDate.ToFileTime();
                request.Name = "a";
                request.To = (uint)toDate.ToFileTime();
                try
                { return mt.DailyReportsRequest(request, logins); }
                catch(Exception ex)
                { return null; }
            }
}

**Comment by Uriil** [comment]
Please contact me on Skype uriil1987 I will try to assist you
