### ISSUE TITLE
send mail to mt4 terminal

### ISSUE THREAD

**Issue by avibb** [Uriil/MetaTrader4.Manager.Wrapper#100]
Can I send email to MailBox within the terminal By account number?
I tried to play with the function MailSend but I could not, whether it is for that? And how is it used?

Thanks

**Comment by Uriil** [comment]
Yes, this method exactly for this project.

What's the problem?

**Comment by avibb** [comment]
Thanks for the quick response
I tried to write it

`

                var mb = new MailBox();

                mb.Body = "Body test";

                mb.Subject = "Subject test";

                mb.From = "From test";

                mb.To = 1234567890; // account number

                var mbr = metatrader.MailSend(mb, new List<int>() { 1234567890 });
`

He returns 151
And Terminal I do not see new mail.

What do I need to change?

Thanks

**Comment by Uriil** [comment]
do you have "From test" assigned to your manager account?

**Comment by Uriil** [comment]
Try to set sender, confirm that manager account has assigned mailbox to him

**Comment by avibb** [comment]
"From test" This is just an example
How do I get what the manager Assign?

Thanks

**Comment by Uriil** [comment]
You configure it via MT4 Administrator app

**Comment by avibb** [comment]
I'm looking for a way to get it automatically
I saw you could get it CfgRequestManager function, but it returns me an empty list.
Is this function belongs only to the Administrator?

Thanks

**Comment by Uriil** [comment]
Yes, everything that starts with Cfg belongs to administrator
