### ISSUE TITLE
err

### ISSUE THREAD

**Issue by superminipig** [Uriil/MetaTrader4.Manager.Wrapper#101]
var orderNo = 8335465;
 TradeRecord tradeOne = metatrader.TradeRecordGet(orderNo);

or 

 var cur = metatrader.UserRecordGet(2124121744)
================================================
report err:
,未处理P23.MetaTrader4.Manager.Contracts.MetaTraderException
  ErrorCode=2
  HResult=-2146233088
  Message=引发类型为“P23.MetaTrader4.Manager.Contracts.MetaTraderException”的异常。
  Source=P23.MetaTrader4.Manager.ClrWrapper
  StackTrace:
       在 P23.MetaTrader4.Manager.ClrWrapper.TradeRecordGet(Int32 order)
       在 MT4ManagerApi.TradeDemo.Main(String[] args) 位置 C:\Users\liubing\documents\visual studio 2015\Projects\MT4ManagerApi\MT4ManagerApi\TradeDemo.cs:行号 29
       在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       在 System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

  
  
  未处理P23.MetaTrader4.Manager.Contracts.MetaTraderException
  ErrorCode=2
  HResult=-2146233088
  Message=引发类型为“P23.MetaTrader4.Manager.Contracts.MetaTraderException”的异常。
  Source=P23.MetaTrader4.Manager.ClrWrapper
  StackTrace:
       在 P23.MetaTrader4.Manager.ClrWrapper.UserRecordGet(Int32 login)
       在 MT4ManagerApi.TradeDemo.Main(String[] args) 位置 C:\Users\liubing\documents\visual studio 2015\Projects\MT4ManagerApi\MT4ManagerApi\TradeDemo.cs:行号 29
       在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       在 System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by Uriil** [comment]
Please provide me minimal example to reproduce this error

**Comment by superminipig** [comment]
using (var metatrader = new ClrWrapper(new ConnectionParameters
{
	Login = Int32.Parse(ConfigurationManager.AppSettings.Get("username")),
	Password = ConfigurationManager.AppSettings.Get("password"),
	Server = ConfigurationManager.AppSettings.Get("server")
}))
{
	var cur = metatrader.UserRecordGet(2124121744);
	Int32 orderNo = 8335465;
	TradeRecord tradeOne = metatrader.TradeRecordGet(orderNo);    
}

**Comment by Uriil** [comment]
*Get methods works only in pumping mode. 
Please refer to official documentation or check my tests to see how it works

**Comment by superminipig** [comment]
how to change into pumping mode?

**Comment by superminipig** [comment]
using (var metatrader = new ClrWrapper(new ConnectionParameters
            {
                Login = xxx,
                Password = "xxxx",
                Server = "xxxxx"
            }))
            {
                int flag = metatrader.SymbolAdd("EURUSD");
                Console.WriteLine("add symbol price : " + flag + "  " + metatrader.ErrorDescription(flag));

                metatrader.PumpingSwitch(i =>
                {
                    var notifyCode = (PumpingNotificationCodes)i;
                    switch (notifyCode)
                    {
                        case PumpingNotificationCodes.Start:
                            {
                                Console.WriteLine("PumpingNotificationCodes.Start : " + DateTime.Now);
                                TradeRecord tradeOne = metatrader.TradeRecordGet(8335465);
                                var cur = metatrader.UserRecordGet(2124121744);
                                break;
                            }
                        case PumpingNotificationCodes.Stop:
                            {
                                Console.WriteLine("PumpingNotificationCodes.Stop : " + DateTime.Now);
                                break;
                            }
                    }
                });
            }


report the same err.

**Comment by Uriil** [comment]
Is it open trade?

**Comment by superminipig** [comment]
how to call  metatrader.TradeRecordGet(8335465)  in pumping mode?

**Comment by Uriil** [comment]
Do you try to request open trade?

**Comment by superminipig** [comment]
no, I want to query open trade by order number.

**Comment by Uriil** [comment]
Can you query same trade using MT4 Manager application?
Do you have manager access to server?

**Comment by superminipig** [comment]
private static void HoldTrade(ClrWrapper metaTrader)
        {
            AutoResetEvent auto = new AutoResetEvent(false);
            var flag=metaTrader.PumpingSwitch((int code)=>{
                var notifyCode = (PumpingNotificationCodes)code;
                switch (notifyCode)
                {
                    case PumpingNotificationCodes.Start:
                        {
                            
                            //auto.Set();
                            break;
                        }
                    case PumpingNotificationCodes.Stop:
                        {
                            break;
                        }
                    default:
                        {
                            var cur = metaTrader.UserRecordGet(CST_LOGIN);
                            var list = metaTrader.TradesGetByLogin(cur.Login, cur.Group);
                            TradeRecord tradeOne = metaTrader.TradeRecordGet(CST_ORDER_NO);
                            break;
                        }
                }
            });
            Console.WriteLine(flag + " " + metaTrader.ErrorDescription(flag));

            auto.WaitOne();
            
        }



called HoldTrade function.
var cur = metaTrader.UserRecordGet(CST_LOGIN); ------the code is normal;
 var list = metaTrader.TradesGetByLogin(cur.Login, cur.Group);----the code is normal;
  TradeRecord tradeOne = metaTrader.TradeRecordGet(CST_ORDER_NO);-----the code reports the same err. why?

**Comment by Uriil** [comment]
Do you have access to corresponding client group?

Basically I can not tell you where is the problem, because it's about permissions. If you want me to check it, please give me temporary access to server and I will review it
