### ISSUE TITLE
get real-time equity for accounts list

### ISSUE THREAD

**Issue by avibb** [Uriil/MetaTrader4.Manager.Wrapper#102]
I want to get real-time equity for accounts list
I wanted to use the BidAskUpdated event, but it takes a long time to get the list of all transactions and calculate them.
Is there a recommended way to do it.

Thanks

**Comment by Uriil** [comment]
Check methods MarginsGet and MarginLevelGet. They have to be used in pumping mode

**Comment by avibb** [comment]
Thanks

The MarginCallUpdated event is for it?

2017-01-26 12:52 GMT+02:00 Nikita Gusev <notifications@github.com>:

**Comment by Uriil** [comment]
No MarginCallUpdated is rised after stop outs or margin calls
