### ISSUE TITLE
Setting magic in opening order

### ISSUE THREAD

**Issue by avibb** [Uriil/MetaTrader4.Manager.Wrapper#103]
Is it possible to set a magic number of the order, like opening a order using AE?

**Comment by Uriil** [comment]
Kind of. You can do it with AdmTradeRecordModify but I am not sure if it's exactly what you want

**Comment by avibb** [comment]
I can not use this function
I wrote it and it fails:
`
        var tr = new TradeRecord();
        tr.Order = myTicket;
        tr.Comment = myComment;
        metatrader.AdmTradeRecordModify(tr);
`

**Comment by Uriil** [comment]
You have to provide all parameters. 
Usually what I was doing is Request entire trade, modify properties and send it's back

**Comment by avibb** [comment]
Thanks for the comment

Still not going
I get a **151** number, what can I do?

**Comment by Uriil** [comment]
Hmm, maybe it's not possible... because I can not change it with MT4 Administrator

**Comment by avibb** [comment]
And change only the comment?
That it is also possible in MT4 manager

Thanks

**Comment by Uriil** [comment]
Did you try to use same method?

**Comment by avibb** [comment]
I tried
Same error

**Comment by Uriil** [comment]
Here is code which is working for me:

    var tradeRecord = mt.TradeRecordsRequest(new List<int>{ 3292 }).Single();
    tradeRecord.Comment = "test";
    var result = mt.AdmTradeRecordModify(tradeRecord);

And same code works for me, if I want to change Magic number

**Comment by avibb** [comment]
I'm trying
But it does not work

There needed a special definition for a function that starts at Adm?

Thanks

**Comment by Uriil** [comment]
Do you have full admin rights to server?

Can you change comment using MT4 Administrator tool?

**Comment by avibb** [comment]
> I think so

By using the Mt4 manager I can change the comment

**Comment by Uriil** [comment]
I think MT4 manager uses different method: TradeTransaction.

U can try using it as well, but it's not that flexible

**Comment by Uriil** [comment]
Do you have any other questions?

**Comment by avibb** [comment]
Thank you very much for all your help!
