### ISSUE TITLE
MarginLevelGet throws ex

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#105]
MarginLevelGet method throws exception if result != RET_OK.

According to MQ documentation "For accounts that have not had any open positions for the connection period, MarginLevelGet() returns RET_ERROR"

Can you please remove the exception as this is normal behavior as it crashes the underlying app?

Thanks

**Comment by miho99** [comment]
Actually it is implemented wrong. It should return error code and get the item by reference

**Comment by Uriil** [comment]
What if in case of RET_ERROR I will return null?

So it will be:
1) MarginData if everything ok
2) null if RET_ERROR
3) exception in any other case

**Comment by miho99** [comment]
no you always return int (Ret) and you pass the MarginLevel as ref - check the managerApi.h
```
virtual int          __stdcall MarginLevelGet(const int login,LPCSTR group,MarginLevel *margin)=0;
```

throwing exception is very expensive for high performance apps
this method will return error by its nature no open position returns RET_ERROR.

**Comment by Uriil** [comment]
But in this case you always will have to verify status code and do appropriate action. Which I don't like.

For example, what you will be doing if response code will 6? or 50? Those are exceptional cases and exception should be thrown.

It would not have impact on performance, if exception will be thrown in rare cases

**Comment by miho99** [comment]
yes it is better to verify in this call. Let me give you my example. 

I have 1000 accounts that I need to check constantly (call MarginLevelGet) on every bid/ask
300 of them do not have open positions thus code returned by MT4 is RET_ERROR. It means that I will receive 300 exceptions. I know MQ sucks on their design but unfortunately we cannot change the manager api. Throwing 300 exceptions is quite heavy

Thanks

**Comment by Uriil** [comment]
Okay, I think you did not get my idea.

1. MarginData if everything ok
2. null if RET_ERROR
3. exception in any other case

In case of RET_ERROR(only this particular error code) I will return null(there will be no exception thrown), so there will be no performance impact.

As you mentioned RET_ERROR are expected error for this method, and there is no need in exception.

But any other ERR_CODE should be treated as exception

**Comment by miho99** [comment]
Although I think the most optimal solution is to follow the ManagerAPi way, I suppose this is a workaround that will work

**Comment by Uriil** [comment]
Done, you can get latest version from develop branch
