### ISSUE TITLE
Error: Failed to create Manager

### ISSUE THREAD

**Issue by avibb** [Uriil/MetaTrader4.Manager.Wrapper#107]
Hi
I try to connect to mt manager using **asp.net web** application
I get the error:
`Failed to create Manager
 Exception thrown: 'P23.MetaTrader4.Manager.Contracts.MetaTraderException' in P23.MetaTrader4.Manager.ClrWrapper.dll`
With this **asp.net core** project works fine, you have no idea why this is happening?

Thanks

**Comment by Uriil** [comment]
Please show code, where u create instance of wrapper

**Comment by avibb** [comment]
```
metatrader = new ClrWrapper(new ConnectionParameters
{
         Login = _login,
         Password = _password,
         Server = _server
});
```
This code works for me in a win forms / asp.net core.
Thanks

**Comment by Uriil** [comment]
Constructor contains second parameter, path to mtmanapi.dll try to provide
it

**Comment by avibb** [comment]
Thank you for your response.
I added the second parameter and it's connect, but immediately took another error
![error](https://cloud.githubusercontent.com/assets/17905501/23353938/9b9b7780-fcd7-11e6-9a2b-885ee35d7bbb.png)
I could not fix it ..

**Comment by Uriil** [comment]
Never had such exception. I suspect there is issue within your code. Please provide me minimal example to reproduce this error

**Comment by avibb** [comment]
I attached a simple example of the connection attempt ASP.NET Web
Application project.
Thank you




2017-02-27 10:44 GMT+02:00 Nikita Gusev <notifications@github.com>:

**Comment by Uriil** [comment]
I don't see attachment

**Comment by avibb** [comment]
He wrote me an error when I attach the file ..
I can send you on Skype?
My skype name is *avi.b600*

Thanks

**Comment by Uriil** [comment]
Drop it to my email: gusevnikita@hotmail.com

**Comment by Uriil** [comment]
Ok, I will check it during next few days and let you know

**Comment by Uriil** [comment]
I've started your application, but don't see any exception, everything works
