### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by timmygod** [Uriil/MetaTrader4.Manager.Wrapper#109]
The issue is appear both on windows service project and MVC project. 
The issue not always happen but randomly happen. 

The exception recorded by the system : 
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at P23.MetaTrader4.Manager.ClrWrapper.!ClrWrapper()
   at P23.MetaTrader4.Manager.ClrWrapper.Dispose(Boolean)
   at P23.MetaTrader4.Manager.ClrWrapper.Finalize()

Seems like ClrWrapper class suddenly become null and when it's going to dispose, it dead. 

Please advice. 
Thanks

**Comment by c0g3nt** [comment]
I don't know if this is of any help. But I faced the same issue a while ago. I believe the reason for this was that event subscriptions were not terminated prior to calling Dispose or Disconnect on the wrapper instance.
  (e.g)=>
` MetaWrapper.BidAskUpdated -= MetaWrapper_BidAskUpdated;`

**Comment by Uriil** [comment]
Please try to create minimal application which will reproduce error. Using it I might be able to help you

**Comment by timmygod** [comment]
I did a lot of work these days. I tried manually dispose the ClrWrapper and add try{} catch{} everywhere, but the issue still happened. 

And I notice that the issue is only happens on windows service. I put the same code in a window console application, and runs 2 days, nothing happens. 

Very weird

**Comment by Uriil** [comment]
Did you start console application from Visual Studio?
