### ISSUE TITLE
No instanse on asp.mvc solution

### ISSUE THREAD

**Issue by nottr0llman** [Uriil/MetaTrader4.Manager.Wrapper#110]
good day! When using this component in the project asp.mvc I get an error not initial instance, please help me...
May be i can use it on wcf service?
And how i can use permanent connection and real-time requests?

**Comment by Uriil** [comment]
Regarding error. I am pretty much sure, that you missing mtmanapi.dll reference in constructor.

Yes you can use it with WCF service

What's the problem with permanent connection?

**Comment by nottr0llman** [comment]
Прошу прощения, можно по русски? :)
по поводу постоянного подключения, не могу додуматься как его использовать...
Библиотека просто замечательная, много чего может, но я не смог понять как мне установить соединение и постоянно получать какие либо данные, например список открытых ордеров, я бы хотел в реальном времени видеть их на сайте...
По поводу ошибки, я ставил пакет через Nuget, и в приложении winforms библиотека mtmanapi.dll была, а в mvc проекте нет...

**Comment by Uriil** [comment]
Создать синглтон с помощью IOC контейнера и использовать его когда нужно.  Либо через статику.

Чтобы получать сообщения о новых ордерах нужно переключиться в пампинг или расширенный пампинг. Но для этого лучше читать документацию метаквотс.

Библиотека там есть, но лучше явно прописать путь в кострукторе ClrWrapper, это будет надежнее
