### ISSUE TITLE
AdmTradesRequest always return 0 elements

### ISSUE THREAD

**Issue by applicazza** [Uriil/MetaTrader4.Manager.Wrapper#111]
Hello, next code always returns 0 elements in list:

client.AdmTradesRequest(login.ToString(), 0);

I have tried to replace login.ToString() with @"*" but still no luck.

Other requests, such as client.UserRecordsRequest() work just perfect.

I am trying to get list of trades that belong to specific trader, without switching to pumping mode.

Is it somehow related to permissions on server? I am successfully connected to server via MT4 Manager and can view/create/modify/delete traders and their trades too.

Thanks!

**Comment by Uriil** [comment]
I order to use this method you have to have full admin rights and should be able to connect using MT4 Administrator
