### ISSUE TITLE
How to Get SymbolInfo directly?

### ISSUE THREAD

**Issue by rebider** [Uriil/MetaTrader4.Manager.Wrapper#112]
I'm using PupingModel, But I can't get symbolinfo until SymbolInfoUpdated().
And how to get symbolinfo on weekend when symbolinfo don't be updated?

**Comment by Uriil** [comment]
Which information exactly do you need?

If you need quotes, you can use: ChartRequest
If you need configuration, you can use: CfgRequestSymbol

Another option, is to cache latest SymbolInfo somewhere and extract it from this place instead of server directly

**Comment by rebider** [comment]
I want to get  CurrentPrice  as soon as possable.

**Comment by Uriil** [comment]
So you can use ChartRequest, but better options is to stream quotes to some cache and extract them later from this place

**Comment by rebider** [comment]
Thanks,I am going to try it,and give you feedback later

**Comment by rebider** [comment]
I have get charts by this method

`Wrapper.ChartRequest(new ChartInfo() { Symbol = symb, Mode = ChartRequestMode.RangeLast, Period = ChartPeriod.M1, End = 1, Start = 0, TimeSign = 0 }, 0);
`

Now the question is I always get charts array that it's array count is 2400.
How can I get the newest chart at 2 mins?
Because I need to get 20 symbols current price at the same time.
Thanks.

**Comment by Uriil** [comment]
You can control interval changing start and end properties.

**Comment by rebider** [comment]
I have tryed ,but it didn't work

**Comment by rebider** [comment]
Could you give me a simple? 
Thanks.

**Comment by Uriil** [comment]
Give me temporary access to your server and email me sample app which does not work

**Comment by rebider** [comment]
What's your email?

**Comment by rebider** [comment]
`
using P23.MetaTrader4.Manager;
using P23.MetaTrader4.Manager.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DemoChartRequest
{
    class Program
    {
        static string[] TakeSymbols = { "USDJPY", "EURUSD", "XAUUSD", "XAGUSD", "AUDUSD", "USCRUDE", "USOil", "USDRMB" };
        static int login;
        static string pass;
        static string server;
        static void Main(string[] args)
        {
            ClrWrapper Wraper = CreateWrapper(login, pass, server);

            do
            {
                foreach (var symb in TakeSymbols)
                {
                    //tem_chars.Count always 2400,I just want 2 newest chart,and i need this data insert into mongodb
                    var tem_chars = Wraper.ChartRequest(new ChartInfo() { Symbol = symb, Mode = ChartRequestMode.RangeLast, Period = ChartPeriod.M1, End = 1, Start = 0, TimeSign = 0 }, 0);
                    if (tem_chars.Count < 1) continue;
                    var lastChart = tem_chars.Last();
                    Console.WriteLine("{0},{1},{2}",symb,lastChart.Ctm,lastChart.Close);
                }
            } while (true);

        }

        public static ClrWrapper CreateWrapper(int login, string password, string server)
        {
            return new ClrWrapper(new ConnectionParameters() { Login = login, Password = password, Server = server },
                @"mtmanapi.dll");
        }

     
    }
}
`
This is my code

**Comment by Uriil** [comment]
Change it to below version:

               var time = Wraper.ServerTime() / 60 * 60 + 60;
                foreach (var symb in TakeSymbols)
                {
                    //tem_chars.Count always 2400,I just want 2 newest chart,and i need this data insert into mongodb
                    var tem_chars = Wraper.ChartRequest(
                        new ChartInfo()
                        {
                            Symbol = symb,
                            Mode = ChartRequestMode.RangeIn,
                            Period = ChartPeriod.M1,
                            End = (uint)time,
                            Start = (uint)time - 60,
                            TimeSign = 0
                        }, 0);
                    if (tem_chars.Count < 1) continue;
                    var lastChart = tem_chars.Last();
                    Console.WriteLine("{0},{1},{2}", symb, lastChart.Ctm, lastChart.Close);
                }

**Comment by rebider** [comment]
Thanks，and I found that MT4 server has server access limit ,It always take me long time when I get many kind of symbols.

**Comment by rebider** [comment]
I can't confirm that it could get all symbols chart in each second.

**Comment by Uriil** [comment]
Never had such issue

**Comment by Uriil** [comment]
Of course it won't... as I told you above. This is slow version, but without intermediate storage. 

Better solution to subscribe to all quotes, store them somewhere and distribute them from this source

**Comment by rebider** [comment]
If I  subscribel to all quotes,how can I sure the connection stable.And if the connection would be disconnected,  and  fix my symbols chart data before reconnected?

**Comment by Uriil** [comment]
In case of disconnect you  can use ChartRequest to rebuild data.

Or you can have to threads, one of them will be fast, building data in real time and second one will be adjusting it if there are some misses using ChartRequest

**Comment by rebider** [comment]
Thanks，I will try this way and give you feedback later.

**Comment by rebider** [comment]
And how long receive timeout that will become disconnect state? Can I config timeout second?

**Comment by Uriil** [comment]
Not sure, you can check official MetaQuotes documentation

**Comment by rebider** [comment]
Thanks a lot.

**Comment by rebider** [comment]
Now I have problem that the last log file was written this
' Remove: manager 53AF938'
I can recoginze this proglem

**Comment by Uriil** [comment]
It means, that manager was disposed

**Comment by rebider** [comment]
Thanks,I found the problem.
