### ISSUE TITLE
The pointer passed in as a string must not be in the bottom 64k of the process's address space

### ISSUE THREAD

**Issue by rachaH** [Uriil/MetaTrader4.Manager.Wrapper#114]
Hi,

I have  an action in a Controller in c# project that calls the metatrader function UserRecordsRequest with a an int list as a parameter(having a prefixed length). 
Whenever i run this action(or any metatrader action) multiple times synchronously it throws the following error and after that it would not respond on any call:
![capture](https://cloud.githubusercontent.com/assets/10095802/25063806/7ab32826-21f6-11e7-8e27-cb48abd45966.PNG)
Example: Two users accessing similar/different actions on metatrader at the **same time**, it throws this exception.

Any help?

Thank you,

**Comment by Uriil** [comment]
Please provide me sample code to reproduce this error

**Comment by rachaH** [comment]
Okay, i have a console app, kind of self hosted web api:
Program.cs: 
![capture](https://cloud.githubusercontent.com/assets/10095802/25066255/dec233d8-2229-11e7-8134-465cd478023b.PNG)

which has also a TestController.cs with the following actions:

1-  Transfer action:

![capture](https://cloud.githubusercontent.com/assets/10095802/25066276/481a51f8-222a-11e7-9921-111492878448.PNG)

2- History action:

![capture](https://cloud.githubusercontent.com/assets/10095802/25066309/0696e81c-222b-11e7-928c-765edba154e2.PNG)

i'm running the exe file of the app and i start call any function .. everything works fine while im just calling it once at a time, however if i call those two functions at the same time, the previous error occurs on the yellow highlighted line.

Thank you,

**Comment by Uriil** [comment]
Mt connection is not thread safe. So you will have to use different one for
each request or lock it

**Comment by rachaH** [comment]
It works fine at first, but when i leave the app running for a few minutes and then i re-call any function, it throws the same error again.

Any idea how to manage working with one connection in a 24/24 running app?
Thank you,

**Comment by wassimhattab** [comment]
Hello,
Does the connection on each request affect the server or get account blocked by the server or something if we have too much users and too much requests?

**Comment by Uriil** [comment]
To keep connection open you need to do something with it(for example use
Ping every N seconds). Of course every connection will utilize some
resources and you will have to figure out how much your server can handle

**Comment by rachaH** [comment]
In the initialization of the app in Program.cs im creating a timer to ping the metatrader every 40 seconds but the timer elapsed function wont be triggered once two functions are called at the same time so the ping is stopped since the timer wont be hit anymore

**Comment by Uriil** [comment]
Use lock to sync it

**Comment by rachaH** [comment]
Does the metatrader server block the account if many connection requests are made at the same time?

Thank you,

**Comment by Uriil** [comment]
No, it's not

**Comment by Uriil** [comment]
Do you still have any problems or we can close this issue?
