### ISSUE TITLE
32bit or 64bit

### ISSUE THREAD

**Issue by magick93** [Uriil/MetaTrader4.Manager.Wrapper#115]
Im looking into if it is possible, and if yes, how, to run the MT4 Manager Wrapper on docker, and as part of this research I need to know if `MetaTrader4.Manager.Wrapper` is 32 or 64bit. I am guessing it is 32bit but would like to confirm.

Thanks

**Comment by Uriil** [comment]
It's 32bit, but you can rebuild it as 64bit

**Comment by liornabat** [comment]
I think the default is 32 bit, you can recompile in 64.
It works both.


Lior,

**Comment by magick93** [comment]
But the metaquotes client dll is 32bit right? The reason I am asking is https://hub.docker.com/r/microsoft/nanoserver/ is only able to run 64 bit applications.

**Comment by Uriil** [comment]
Metaquotes provides two version of their library: mtmanapi.dll and mtmanapi64.dll

**Comment by liornabat** [comment]
Yes, but nano server cannot support .net framework only .net core


Lior,

**Comment by magick93** [comment]
> Yes, but nano server cannot support .net framework only .net core

I realize that. And that is why we are discussing how to solve this on https://github.com/Uriil/MetaTrader4.Manager.Wrapper/issues/113

**Comment by Uriil** [comment]
Closing as duplicate
