### ISSUE TITLE
Extended pumping mode

### ISSUE THREAD

**Issue by prodipgogoi** [Uriil/MetaTrader4.Manager.Wrapper#116]
My extended pumping mode is close in every 2 hours and also it takes long time to start. But i need to continue it forever how can i do it please help.

**Comment by Uriil** [comment]
You need to figure out what's the reason of disconnect. But anyway, there is event PumpingClosed which you can catch in reconnect

**Comment by prodipgogoi** [comment]
Yah i try to restart pumping from this event but it is not working i don't know why.
inside pumping closed event i try to call PumpingSwitchEx(PumpingMode.Reserved); some times its works but most of the time it does not work. and also it takes long tome to start in case of success.

**Comment by Uriil** [comment]
Please provide minimal example to reproduce this error. I am running pumping for weeks, without such issue.
