### ISSUE TITLE
output __time32_t *timesign argument of ChartRequest gets lost in wrapper

### ISSUE THREAD

**Issue by filipdulic** [Uriil/MetaTrader4.Manager.Wrapper#117]
Based on documentation of the original ChartRequest function of the dll __time32_t *timesign argument is an output parameter which the server returns as the timestamp of the requested data. Which you could later use as the timesign property of ChartInfo object to request only updated data from that timesign. 

The Wrapper function ChartRequest in ChartBases.cpp uses the timesign argument as an input argument ,passed to function as a value, instead of as a pointer or reference, and thus the output is lost to a client using the wrapper.

**Comment by Uriil** [comment]
Thank you for you report. I will fix it as soon as possible

**Comment by Uriil** [comment]
I've fixed it and pushed latest version to Nuget.

Please note, that apart from that solution also was retargeted to VC++ 2017.
