### ISSUE TITLE
Вычитка данных из Pumping mode

### ISSUE THREAD

**Issue by nottr0llman** [Uriil/MetaTrader4.Manager.Wrapper#119]
Доброго дня подскажите пожалуйста, может я что-то делаю не так, хочу постоянно получать список актуальных ордеров например, или просто кол-во юзеров онлайн, но ничего не получаю...

Пример кода:

```
var are = new AutoResetEvent(false);
            using (var metatrader = new ClrWrapper(new ConnectionParameters
            {
                Login = 54545,
                Password = "",
                Server = ""
            }))
            {
                metatrader.PumpingSwitchEx(PumpingMode.Default);
                metatrader.OnlineUpdated += (sender1, record) =>
                {
                    
                    listBox1.Items.Add(record.ToString());
                };
                metatrader.PumpingStarted += (sender1, eventArgs) =>
                {

                    are.Set();
                };
                are.WaitOne();
            }
```

**Comment by nshishov** [comment]
Проверьте права менеджера и группы которые видит менеджер.

**Comment by nottr0llman** [comment]
Менеджер доступ полный, так же под админом пробовали и ничего... Может я как то не так пишу? Хотя грубо говоря код - копия из readme. Полная копия из описания не завелась вообще, ибо требовалось указать св-во пампинга. У вас есть рабочий пример, которым вы можете поделиться? Буду благодарен...

**Comment by nshishov** [comment]
```
AutoResetEvent pumpConnected = new AutoResetEvent(false);

ClrWrapper mt = new ClrWrapper(new ConnectionParameters { Server = server, Login = login, Password = password });
mt.SymbolsRefresh();

mt.PumpingStarted += (s, e) =>
{
	pumpConnected.Set();
};

mt.OnlineUpdated += (s, e) =>
{
	Console.WriteLine(e.ToString());
};

mt.PumpingSwitchEx(PumpingMode.Default);

pumpConnected.WaitOne();

Console.WriteLine("Pumping enabled");
Console.WriteLine("Press any key to disconnect");
Console.ReadKey();
mt.Disconnect();
```

**Comment by nottr0llman** [comment]
Спасибо за пример! Сейчас опробую, отпишу... и еще вопрос, обязательно собирать сборки из репозитария? В nuget актуальная версия?

**Comment by nshishov** [comment]
Я заметил баг в этом событии.
Cоздал pull request https://github.com/Uriil/MetaTrader4.Manager.Wrapper/pull/121

**Comment by nottr0llman** [comment]
Спасибо огромное! правильно ли я понимаю, если не делать
`mt.Disconnect();`
то, при изменении кол-ва пользователей - будет вывод в консоль по средством
```
mt.OnlineUpdated += (s, e) =>
            {
                Console.WriteLine(e.ToString());
            };
```
И будет ли это работать для других объектов mt?
Вот к примеру как я писал выше для ордеров? просто не нашел данной инфорации, как эти данные получить

**Comment by nshishov** [comment]
Это просто правильное отключение перед завершением программы.
По ордерам подписывайтесь на необходимые события Trade* и получите список открытых через TradesGet

**Comment by nottr0llman** [comment]
Ага, это понятно! я подписался на 
```
mt.TradeAdded += (s, e) =>
            {
                pumpConnected.Set();
            };

            mt.RequestInfoUpdated += (s, e) =>
            {
                Console.WriteLine(e.Login.ToString());
            };
```
Захотел получить инофрмацию какой логин открыл сделку - но в ответ пустота, mt отключился

**Comment by nshishov** [comment]
Всё есть, ищите лучше ;)

**Comment by nottr0llman** [comment]
Нашел :)
Можно еще вопросик, как нибудь можно дебажить этот процесс? с потоками мало работал, может есть какой-либо механизм. Точка останова не помогает :(

**Comment by nshishov** [comment]
У меня спокойно везде останавливается, вы в Debug режиме собираете?

**Comment by nottr0llman** [comment]
![default](https://cloud.githubusercontent.com/assets/26642317/25710304/13226558-3116-11e7-9152-2ae19c264722.png)
Да, конечно

**Comment by nshishov** [comment]
Ох... Ознакомтесь с примерами которые идут вместе с менджерским dll.

Вы пытаетесь получить список всех открытых ордеров в событии обновлении одного ордера, это в корне не правильно.

Вам нужно:
1) Подписаться на события добавления, обновления и удаления ордеров.
2) Подключиться к серверу
3) Переключиться в пампинг
4) Запросить открытые ордера

Я как понимаю вы новичёк в программировании или C#? Ознакомтесь в начале с теорией.

**Comment by nottr0llman** [comment]
Не новичек) спасибо за наводки, пойду лучше отдохну и завтра со свежей головой напишу то чего хотел... Огромное спасибо, Николай

**Comment by nshishov** [comment]
Просто не часто увидишь студию на русском языке =)

**Comment by nottr0llman** [comment]
да, есть грешок))) Удачного дня!
