### ISSUE TITLE
Unable to get MD5 checksum for the key file "signkey.pfx"

### ISSUE THREAD

**Issue by beedge72** [Uriil/MetaTrader4.Manager.Wrapper#12]
I have tried to add this repo as a dependency to an existing project, however when I try and build in VS13 I get the following error:

`
Error	1	Unable to get MD5 checksum for the key file "signkey.pfx". Could not find file 'C:\Work\RzrCbf\MetaTrader4.Manager.Wrapper\src\P23.MetaTrader4.Manager.Contracts\signkey.pfx'.`

Checking the directory manually, the file does not exist there

**Comment by Uriil** [comment]
Yeah, I don't want to share private key. But you can turn off assembly signing for both projects: https://msdn.microsoft.com/en-us/library/xc31ft41(v=vs.110).aspx
