### ISSUE TITLE
Update API to version 1065?

### ISSUE THREAD

**Issue by AhmadZuhdi** [Uriil/MetaTrader4.Manager.Wrapper#123]

**Comment by Uriil** [comment]
I will try to do it during this week

**Comment by knax** [comment]
Can i create pull request for this one?

**Comment by Uriil** [comment]
sure

**Comment by Uriil** [comment]
I've merged it and will update nuget package tonight

**Comment by nshishov** [comment]
I update wrapper itself, instead of just libs #125

**Comment by Uriil** [comment]
Merged and pushed changes
