### ISSUE TITLE
Not compatible with NETCoreApp

### ISSUE THREAD

**Issue by nguyenchiencong** [Uriil/MetaTrader4.Manager.Wrapper#126]
Package MetaTrader4.Manager.Contracts 0.4.6337.32332 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package MetaTrader4.Manager.Contracts 0.4.6337.32332 supports: net (.NETFramework,Version=v0.0)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.

**Comment by Uriil** [comment]
Yes it is not. There is separate discussion about migration: [#113](https://github.com/Uriil/MetaTrader4.Manager.Wrapper/issues/113)

**Comment by nguyenchiencong** [comment]
Thanks
