### ISSUE TITLE
CfgUpdateGroup problem

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#127]
When I insert a new item in the Group.SecMargins and call CfgUpdateGroup I get retOk but I cannot see the item on admin terminal even if I restart the server. 
Strange thing is that after calling CfgUpdateGroup I call CfgRequestGroup and I can see the item in the list but not in admin terminal.

**Comment by nshishov** [comment]
Did you update SecMarginsTotal ?

**Comment by miho99** [comment]
Thanks
