### ISSUE TITLE
How to integrate with Rest API

### ISSUE THREAD

**Issue by thilak1984** [Uriil/MetaTrader4.Manager.Wrapper#129]
Hello Uriil,

I am php developer so i am new to .net application. can you provide me step by step how to install your mt4manager API.

And main question: Can you please tell me how to integrate rest api method to your mt4manager api ?

**Comment by Uriil** [comment]
To install it you have to can use Nuget or add reference to your project(.NET project)

You have to create REST API yourself. For example you can do it using [ASP.NET WebAPI](https://www.asp.net/web-api).

**Comment by thilak1984** [comment]
Thank you for your kind reply. can i have your skype ID please. I need to do some more project for mt4 platform

**Comment by Uriil** [comment]
uriil1987
