### ISSUE TITLE
Running Tests fails. Cannot find configuration file

### ISSUE THREAD

**Issue by beedge72** [Uriil/MetaTrader4.Manager.Wrapper#13]
When running the test suite all tests fails. 

`Could not find file 'C:\Work\DNNPlayGround\MetaTrader4.Manager.Wrapper\src\P23.MetaTrader4.Manager.Tests\credentials.config'.`

I presume you simply have not included a credentials.config file for security purposes 

can we at least include a config.template file so that the correct syntax is apparent?

**Comment by Uriil** [comment]
Sure, I will add it tomorrow and provide a bit of description

**Comment by beedge72** [comment]
Fantastic thank you, although looking at the code, am I right in saying that I just need to supply a file with teh following line:

`login,password,server`

**Comment by Uriil** [comment]
Don't remember exact order, but yeah

**Comment by Uriil** [comment]
Added readme to text project(develop branch)
