### ISSUE TITLE
pumping switch ex function

### ISSUE THREAD

**Issue by sysem85** [Uriil/MetaTrader4.Manager.Wrapper#130]
i guess the input variable of pumping switch ext function should not be limited to PumpingMode data type, it should be of int type so that it could have mixed pumping mode. (e.g. hideNews || hideMail , etc...)

int PumpingSwitchEx(P23::MetaTrader4::Manager::Contracts::PumpingMode pumpingMode);

**Comment by Uriil** [comment]
PumpingMode enum marked with `FlagsAttribute`, so you can do exactly what you talking about. You can check [msdn](https://msdn.microsoft.com/en-us/library/system.flagsattribute(v=vs.110).aspx) to see how it works

**Comment by sysem85** [comment]
thanks
