### ISSUE TITLE
ClrWrapper Instancing Issue

### ISSUE THREAD

**Issue by fabry1** [Uriil/MetaTrader4.Manager.Wrapper#131]
I'm tryng to familiarize with P23.MetaTrader4.Manager.ClrWrapper and using same credentials of MT4
i get an Error during instancing ClrWrapper:
mt = new ClrWrapper(conParam) => Failed to instantiate manager instance
Which set up is required?

**Comment by Uriil** [comment]
Do you have valid manager credentials? Can you confirm that you can connect using MT4 Manager?

**Comment by fabry1** [comment]
I use regularly metatrader4 with success.
I tried to instance ClrWrapper with same credentials: account, pwd, server:port getting the exception message Failed to instantiate manager instance. What can I check or do?

**Comment by Uriil** [comment]
It's manager API and you have to provide manager credentials

**Comment by fabry1** [comment]
Is there any way to acces to server as metarader4.like access ? 
or manager API is something provided by broker side?

**Comment by Uriil** [comment]
Manager API is only for brokers

**Comment by fabry1** [comment]
Is there a way to build in c# a thin "metatrader" client?

**Comment by Uriil** [comment]
I don't know about such possibility and you will have to research it on your own

**Comment by fabry1** [comment]
ok Uriil, thank you.
