### ISSUE TITLE
TradeCalcProfit

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#132]
Has anyone manage to use TradeCalcProfit successfully because I try and I always get profit = 0

**Comment by nshishov** [comment]
Fixed #133

**Comment by miho99** [comment]
@nshishov When I pass the traderecord object to the TradeCalcProfit method this code is evalued and exception is thrown

 ```
   if (input->ConvRates->Count != 2) {
        throw gcnew ArgumentException("Number of ConvRates should be equal to 2", "input.ConvRates");
    }

```

The same also happens for conversion of ApiData field

**Comment by nshishov** [comment]
Just fill these lists with zero values, this happens because wrapper expects filled lists.

**Comment by miho99** [comment]
I do it like this but it is a hack :)

**Comment by Uriil** [comment]
@miho99 How do you want me to solve it? TradeRecord->ConvRates always has to have two values(and there are some other objects with similar issues, ex sessions in symbol configuration)

**Comment by nshishov** [comment]
I think you should allow to have ConvRates and ApiData setted to null, that will just mean that they should be default - "0"
I can make commit if you want.

**Comment by Uriil** [comment]
Okay, but what is somebody will provide just one value?

**Comment by nshishov** [comment]
Just null or filled list with requred number of items.

**Comment by Uriil** [comment]
ok, you can create pull request

**Comment by nshishov** [comment]
Done, check it please #134

**Comment by Uriil** [comment]
Merged, I will create and publish nuget package a bit later

**Comment by miho99** [comment]
Maybe create an overload for this call

**Comment by miho99** [comment]
Uriil can you merge into master?

**Comment by Uriil** [comment]
done

**Comment by miho99** [comment]
Thank you
