### ISSUE TITLE
ManagerCommon function

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#136]
Hi,

Is ManagerCommon commented code the correct one?

**Comment by nshishov** [comment]
Reuse content and method signature of CfgRequestCommon for this method.

**Comment by Uriil** [comment]
I've implemented this method, you can check it.

**Comment by miho99** [comment]
Thanks Uriil tested it and it works. Can you please merge into master?

**Comment by Uriil** [comment]
Done
