### ISSUE TITLE
MT 5 server

### ISSUE THREAD

**Issue by DifficultPhil** [Uriil/MetaTrader4.Manager.Wrapper#138]
Доброго дня, подскажите пожалуйста, ваша библиотека будет работать с MT5 сервером? Или придется переписывать под новое api?
Заранее спасибо

**Comment by nshishov** [comment]
MQ выпустили свой собственный враппер для .Net для MT5

**Comment by DifficultPhil** [comment]
не подскажите где можно посмотреть информацию о нём или скачать?

**Comment by nshishov** [comment]
С их сайта поддержки.

**Comment by DifficultPhil** [comment]
еще один вопрос, он находится в закрытой части сайта поддержки? простому смертному не попасть, верно?)

**Comment by nshishov** [comment]
Верно.

**Comment by DifficultPhil** [comment]
спасибо!
