### ISSUE TITLE
UserRecordGet throws unknown exception

### ISSUE THREAD

**Issue by beedge72** [Uriil/MetaTrader4.Manager.Wrapper#14]
Ive been writing tests to check the functionality of functions that would be useful to me in an application that is being built, and Ive come across a few unknown exceptions being thrown, specifically:
```
[Test]
        public void UserRecordGetTest()
        {
            var config = ConfigurationManager.AppSettings["credentials"].Split(',');
            var mtmanapiPath = ConfigurationManager.AppSettings["mtmanapiPath"];
      
            var connectionParameters = new ConnectionParameters
            {
                Login = int.Parse(config[0]),
                Password = config[1],
                Server = config[2]
            };
            using (var metatrader = new ClrWrapper(connectionParameters, mtmanapiPath))
            {
                UserRecord user = metatrader.UserRecordGet(Int32.Parse("411168"));
                Console.WriteLine("user:" + user.Name);
            }

        }
```

Results in : 

> P23.MetaTrader4.Manager.Contracts.MetaTraderException : Exception of type 
> 'P23.MetaTrader4.Manager.Contracts.MetaTraderException' was thrown.
> 
>    at P23.MetaTrader4.Manager.ClrWrapper.UserRecordGet(Int32 login)
>    at InstantRebates.MTServer.Tests.MTWrapperTest.UserRecordGetTest() in C:\Work\project
> \MTServer\Tests\MTWrapperTest.cs:line 115

**Comment by Uriil** [comment]
Methods with name *Get requires pumping mode (I think I have some tests implemented)

**Comment by beedge72** [comment]
My understanding is that pumping works when the recorded is updated on the MetaServer, is that correct? what if I simply want to retrieve the record a single UserRecord?

**Comment by Uriil** [comment]
It works both way. Basically it connects to server, loads everything into memory and allows you to query it.
To get single user you need to use UserRecordsRequest(non pumping) and UserRecordGet(pumping).
