### ISSUE TITLE
memory leak after Real time ticks 

### ISSUE THREAD

**Issue by ntyl82** [Uriil/MetaTrader4.Manager.Wrapper#140]
hi uriil ,
I have a service that has memory leak. After Real time ticks
 using (var mt = TestHelpers.CreateWrapper())
        {
            var autoResetEvent = new AutoResetEvent(false);
            var symbols = mt.CfgRequestSymbol();
            mt.SymbolsRefresh();
            foreach (var symbol in symbols)
            {
                mt.SymbolAdd(symbol.Name);
            }
            mt.PumpingSwitchEx();
            
            mt.BidAskUpdated += (sender, args) =>
            {
                var total = 0;
                do
                {
                    var symbolsInfos = mt.SymbolInfoUpdated();
                    foreach (var symbolInfo in symbolsInfos)
                    {
                        Console.WriteLine("{0} {1} {2}", DateTime.Now, symbolInfo.Symbol, symbolInfo.Bid);
                        
                    }
                    total = symbolsInfos.Count;
                } while (total > 0);
            };

            autoResetEvent.WaitOne();
        }
I dont know why ，pelease

**Comment by nshishov** [comment]
No leak in this method, maybe you keep references to ticks somewhere?
And for tick data I suggest you to use TickInfoLast with null as argument to request ticks for all subscribed instruments.

**Comment by miho99** [comment]
@ntyl82 post some more code.
