### ISSUE TITLE
unhandled exception on UserRecordsRequest function

### ISSUE THREAD

**Issue by li0803** [Uriil/MetaTrader4.Manager.Wrapper#143]
I call UserRecordsRequest function in 1 second interval in loop. and after about 20 or 30 calls, the exception occurs. here is the exception content:

> An exception of type 'System.ArgumentException' occurred in P23.MetaTrader4.Manager.ClrWrapper.dll but was not handled in user code
Additional information: The pointer passed in as a String must not be in the bottom 64K of the process's address space.
If there is a handler for this exception, the program may be safely continued.

The error seems is clear. But I totally don't understand what does it mean.

**Comment by Uriil** [comment]
This error comes from unmanaged and basically means that one of string properties of userRecord class was broken. Is it reproducible for you? I was trying to catch it but always was failing...

**Comment by li0803** [comment]
Yes. I got it from my managed code. My UserRecordsRequest function is called in a infinite loop in every one second. The first 20~30 calls work fine, but after that, all of calls throw that exception.

I wiil past my code when back to my computer. Hope that help.

**Comment by li0803** [comment]
Here is my code
`public UserRecord Get(int userLogin, int? managerId = null)
        {
            TryGetWrapper(managerId);
            UserLoginsList.Clear();
            UserLoginsList.Add(userLogin);
            var result = managerWrapper.RequestWrapper.UserRecordsRequest(UserLoginsList).FirstOrDefault();
            return result;
        }`

It is called in every 1 second. And the exception will be thrown after 20~30 calls.

However, when the calling interval is changed from 1 second to 2 second. The exception is seldon thrown out. But still there is one exception in every about 40 calls.

**Comment by Uriil** [comment]
Below is the sample code, which does not throw exception for me:

    using (var wrapper = new ClrWrapper(new ConnectionParameters
    {
        Server = "127.0.0.1",
        Login = 1,
        Password = "password1"
    }))
    {
        var users = wrapper.UsersRequest();
        foreach (var userRecord in users)
        {
            var user = wrapper.UserRecordsRequest(new List<int> {userRecord.Login}).Single();
            Console.WriteLine(user.Login);
        }
    }

You can try it, and if it works, there is problem with your code. If it's not, and you want me to investigate it, I will need temporary access to your server, because I don't this this issue with mine
