### ISSUE TITLE
OnlineUpdated wrong login

### ISSUE THREAD

**Issue by dekaskas** [Uriil/MetaTrader4.Manager.Wrapper#144]
On PUMP_UPDATE_ONLINE
the int cast shoud be
int onlineLogin = *(int*)data;
instead of:
int onlineLogin = PtrToInt(data);

so the onlineLogin be the value of the pointed value instead of the pointer value

**Comment by Uriil** [comment]
That's how it was implemented initially, but it was changed later by @nshishov

**Comment by dekaskas** [comment]
Ok, a correction
`int onlineLogin = *(int*)data;`
casting to int and PtrToInt return the value of the pointer
but it needs to be dereferenced

**Comment by nshishov** [comment]
Already fixed, #121

**Comment by dekaskas** [comment]
But PtrToInt  is not a derefrence
it is still a cast to int

**Comment by nshishov** [comment]
Hmmm, looks like you are right.
