### ISSUE TITLE
about Pumping execution exception 

### ISSUE THREAD

**Issue by anymorefree** [Uriil/MetaTrader4.Manager.Wrapper#146]
when I use PumpingSwitchEx() like this: 
{
mt.PumpingSwitchEx(PumpingMode.Default);
                mt.BidAskUpdated += (sender, eventArgs) =>
                {
                    Console.WriteLine("line......");
                    autoResetEvent.Set();
                };
                autoResetEvent.WaitOne();
}
I find the callback  execute Only twice，Is that why?

**Comment by Uriil** [comment]
Your code is okay, probably the problem is somewhere else
