### ISSUE TITLE
about TradeTransaction method ,help!

### ISSUE THREAD

**Issue by anymorefree** [Uriil/MetaTrader4.Manager.Wrapper#147]
i try add a order use TradeTransaction method  like this:

 var tti = new TradeTransInfo
                {
                    //Cmd = TradeCommand.Buy,
                    OrderBy = 10000, //login
                    Volume=1,
                    Order = 540116,// order number
                    Type = TradeTransactionType.OrderCloseBy
                };
                //Act
                var result = mt.TradeTransaction(tti);

unlucky, I got the result is 7,"invaliding parameters". Have you ever met this question? 
Please help me analyze this question, thank you.

**Comment by Uriil** [comment]
Use TtBrOrderClose, not OrderCloseBy, ClosyBy means that you want to close order using another

**Comment by anymorefree** [comment]
yes,I changed to BrOrderClose,  also the result is "invaliding parameters" ,the parameters are 
                  OrderBy = 10000, //login
                    Order = 540116,// order number
                    Type = TradeTransactionType.BrOrderClose

anything else?

**Comment by Uriil** [comment]
You missed Price parameter

**Comment by anymorefree** [comment]
oh! yes,think you.
