### ISSUE TITLE
SymbolInfoGet(s.Name) causing Exception of Type

### ISSUE THREAD

**Issue by mrwillt1986** [Uriil/MetaTrader4.Manager.Wrapper#149]
When trying to pull specific symbol info its possible to get a list of all symbol names using SymbolsGetAll but when looping through these and trying to get symbol specific information the following exception is thrown:

Exception of type 'P23.MetaTrader4.Manager.Contracts.MetaTraderException' was thrown.

Example code to reproduce:

```
metatrader.SymbolsRefresh();
                                                        
IList<Symbol> symbols = metatrader.SymbolsGetAll();
                            
foreach (Symbol s in symbols)
{
 try
 {
  SymbolInfo thisSymbol = metatrader.SymbolInfoGet(s.Name);
 }
 catch (Exception e)
 {
   Console.WriteLine(e.Message);
 }
}
```

**Comment by Uriil** [comment]
`SymbolInfoGet` requires pumping mode

**Comment by mrwillt1986** [comment]
Ah! Thanks Uriil
