### ISSUE TITLE
dependency for the wrapper

### ISSUE THREAD

**Issue by sysem85** [Uriil/MetaTrader4.Manager.Wrapper#15]
i cannot build your project using vs2012.

any dependency for the wrapper??

**Comment by Uriil** [comment]
It's created in vs2013, that's why you see error.
To build in vs2012:
1. Reduce platform toolset version to your one
2. Disable assembly signing

**Comment by sysem85** [comment]
i have tried to reduce the platform toolset version to vs2012 (v110)
but it stills have > 80 errors when compiling the P23.MetaTrader4.Manager.ClrWrapper.

Is it possible that a VS2012 version available ??

**Comment by Uriil** [comment]
OK, I don't have vs2012, but just checked in vs2010. And also see 80 errors. If you look at them, they complain about two things: initializing variables (numberofsecondsinday and callbackhandler) and constructor. I'am sorry but I don't have time and resources to downgrade version... So you will have to deal with it on your own
