### ISSUE TITLE
help

### ISSUE THREAD

**Issue by YZBGitHub** [Uriil/MetaTrader4.Manager.Wrapper#150]

**Comment by YZBGitHub** [comment]
i need P23.MetaTrader4.Manager.ClrWrapper.DLL for x64 version.

**Comment by YZBGitHub** [comment]
i want to watching the trader ,when new trader ,i can receive msg,so i can  update  to my database.
but i use this code cant'  
`     var are = new AutoResetEvent(false);

            using (var metatrader = new ClrWrapper(new ConnectionParameters
            {
                Login = 817,
                Password = "Tp8avxX",
                Server = "tdlive1.tidealing.net:443"
            }, AppDomain.CurrentDomain.BaseDirectory + @"lib\mtmanapi.dll"))
            {

                metatrader.PumpingSwitchEx(0);
                metatrader.TradeAdded += (sender, record) =>
                {
                    Console.WriteLine(record);
                };
                metatrader.UserUpdated += (sender, record) =>
                {
                    Console.WriteLine(record);
                };

                metatrader.TradeUpdated += (sender, record) =>
                {
                    Console.WriteLine(record);
                };
                
                metatrader.PumpingStarted += (sender, eventArgs) =>
                {
                    are.Set();
                };


                are.WaitOne();

            }`

**Comment by YZBGitHub** [comment]
i want to watching the trader ,when new trader ,i can receive msg,so i can update to my database.
but i use this code cant'
`     var are = new AutoResetEvent(false);

            using (var metatrader = new ClrWrapper(new ConnectionParameters
            {
                Login = 8xx,
                Password = "TpxxxxxxX",
                Server = "tdxlivexxxxdexixxxxxng.net:443"
            }, AppDomain.CurrentDomain.BaseDirectory + @"lib\mtmanapi.dll"))
            {

                metatrader.PumpingSwitchEx(0);
                metatrader.TradeAdded += (sender, record) =>
                {
                    Console.WriteLine(record);
                };
                metatrader.UserUpdated += (sender, record) =>
                {
                    Console.WriteLine(record);
                };

                metatrader.TradeUpdated += (sender, record) =>
                {
                    Console.WriteLine(record);
                };
                
                metatrader.PumpingStarted += (sender, eventArgs) =>
                {
                    are.Set();
                };


                are.WaitOne();

            }`

**Comment by Uriil** [comment]
And what's the problem?

**Comment by YZBGitHub** [comment]
`  metatrader.TradeAdded += (sender, record) =>
            {
              //why the programe cant't into this when the event occur
                Console.WriteLine(record);
            };`

**Comment by YZBGitHub** [comment]
What should I do?
I want to do I can get the message when the transaction is processing?

**Comment by YZBGitHub** [comment]
@Uriil .could you help me?thank you

**Comment by Uriil** [comment]
Your recent code exits right after pumping start. I can help you with problems related to API, but I can not write code for you

**Comment by YZBGitHub** [comment]
what's is mean "Your recent code exits right after pumping start"?
`   using (var metatrader = new ClrWrapper(new ConnectionParameters
            {
                Login = 817,
                Password = "Tp8avxX",
                Server = "tdlive1.tidealing.net:443"
            }, AppDomain.CurrentDomain.BaseDirectory + @"lib\mtmanapi.dll"))
            {
                var are = new AutoResetEvent(false);
                var are1 = new AutoResetEvent(false);
                var are2 = new AutoResetEvent(false);
                var are3 = new AutoResetEvent(false);

                metatrader.PumpingSwitch(i =>
                {
                    if ((PumpingNotificationCodes)i == PumpingNotificationCodes.Start)
                    {
                        are.Set();
                    }
                    if ((PumpingNotificationCodes)i == PumpingNotificationCodes.Stop)
                    {
                        are1.Set();
                    }
                    if ((PumpingNotificationCodes)i == PumpingNotificationCodes.Trades)
                    {
                        are2.Set();
                    }
                    if ((PumpingNotificationCodes)i == PumpingNotificationCodes.Users)
                    {
                        are3.Set();
                    }
                });




                are.WaitOne();
                are1.WaitOne(new TimeSpan(0, 0, 10));
                are2.WaitOne(new TimeSpan(0, 0, 10));
                are3.WaitOne(new TimeSpan(0, 0, 10));


            }`

**Comment by YZBGitHub** [comment]
the demo code is
`var are = new AutoResetEvent(false);
	using (var metatrader = new ClrWrapper(new ConnectionParameters
			{
				Login = 123456,
				Password = "managerPassword",
				Server = "123.123.123.123:443"
			}))
	{
		metatrader.PumpingSwitchEx();
		metatrader.TradeAdded += (sender, record) =>
		{
			Console.WriteLine(record);//i can do it when the TradeAdded occur?
		};
		metatrader.PumpingStarted += (sender, eventArgs) =>
		{
			are.Set();
		};
		are.WaitOne();
	}`
it is mean that i can do it when the TradeAdded occur?

**Comment by YZBGitHub** [comment]
the demo code is
`var are = new AutoResetEvent(false);
	using (var metatrader = new ClrWrapper(new ConnectionParameters
			{
				Login = 123456,
				Password = "managerPassword",
				Server = "123.123.123.123:443"
			}))
	{
		metatrader.PumpingSwitchEx();
		metatrader.TradeAdded += (sender, record) =>
		{
			Console.WriteLine(record);
		};
		metatrader.PumpingStarted += (sender, eventArgs) =>
		{
			are.Set();
		};
		are.WaitOne();
	}`
it is mean that i can do it when the TradeAdded occur?

**Comment by YZBGitHub** [comment]
what's is mean "Your recent code exits right after pumping start."

**Comment by Uriil** [comment]
Okay, why do you have this code:

    are.Set();

What's your goal of using it?

**Comment by YZBGitHub** [comment]
Oh!!!!   i see....thank you very much
