### ISSUE TITLE
Need Help to find symbols for a group

### ISSUE THREAD

**Issue by lukeshp84** [Uriil/MetaTrader4.Manager.Wrapper#151]
I am trying to find symbols available to a group. I am able to get group securities for a symbol and able to get list of symbols and their securities. but i can not map symbol security with group securities.
Has anyone done this before?

**Comment by Uriil** [comment]
They mapped by index, here is sample, to get the idea:

    var symbols = manager.CfgRequestSymbol();
    var groups = manager.CfgRequestGroup();
    var availableSymbolGroups = new HashSet<int>(groups.Single(p => p.Name == "GroupName").SecGroups.Select(p => new {Index = i, Trade = p.Trade}).Where(p => p.Trade == 1).Select(p => p.Index).ToList());
    var availableSymbols = symbols.Where(p => availableSymbolGroups.Contains(p.Type));

**Comment by lukeshp84** [comment]
Thanks man. I took a longer route to find the same info.
