### ISSUE TITLE
The project is missing file  signkey.snk

### ISSUE THREAD

**Issue by respringwa** [Uriil/MetaTrader4.Manager.Wrapper#152]
The project is missing file
MetaTrader4.Manager.Wrapper-master\src\P23.MetaTrader4.Manager.ClrWrapper\signkey.snk

Is anyboby have?

**Comment by Uriil** [comment]
It's on purpose. If you need to rebuild it, you can disable dll signing

**Comment by respringwa** [comment]
@Uriil How to do it?

**Comment by respringwa** [comment]
done
