### ISSUE TITLE
Getting All trades

### ISSUE THREAD

**Issue by lukeshp84** [Uriil/MetaTrader4.Manager.Wrapper#153]
Hi Uriil,

I have a requirement of getting all the trades from mt4 server. I'm trying to do this with TradesRequest, but it doesn't seem to get all the trades. My restriction is that i can not use admin functions. can you suggest me how i can do this. Please suggest.

**Comment by Uriil** [comment]
Try using method ReportsRequest. I think you can get all closed trades
using it + Trades request will return you all open trades
