### ISSUE TITLE
Exception of type 'P23.MetaTrader4.Manager.Contracts.MetaTraderException' was thrown.

### ISSUE THREAD

**Issue by tripathv** [Uriil/MetaTrader4.Manager.Wrapper#154]
Hi 
I have a list of trades and I am looping through and calling TradeRecordGet to get updated value. Its in pumping ext mode - MetaTrader.PumpingSwitchEx(PumpingMode.Default);

But for some of the trades  I am getting an exception is thrown - Exception of type 'P23.MetaTrader4.Manager.Contracts.MetaTraderException' was thrown.

As there are no other information, its hard to debug and find out root cause.

Any ideas?

**Comment by Uriil** [comment]
MetaTraderException contains property ErrorCode, check what is it and correlate with MQ errors list
