### ISSUE TITLE
get user real-time balance?

### ISSUE THREAD

**Issue by anymorefree** [Uriil/MetaTrader4.Manager.Wrapper#155]
Is there a way to get the user's real-time balance and margin ratio?

**Comment by Uriil** [comment]
Kind of. We were doing in two ways, both of them require pumping mode:
1) near-realtime option, you can request margins every second, it won't impact trade server and it's similar to mtm
2) you can always calculate balance and margin based on open trades and real-time ticks

**Comment by anymorefree** [comment]
Thank you very much for your reply, and now I am going to adopt the second way, but this requires a good design architecture, because the amount of data is very large
