### ISSUE TITLE
ClrWrapper  namespace missing

### ISSUE THREAD

**Issue by kwiksys** [Uriil/MetaTrader4.Manager.Wrapper#157]
I am having issues in the above.

I am using VS 2015 and used nuget to install MetaTrader4.Manager.Wrapper in the references section.
I can see two dll references

1) P23.MetaTrader4.Manager.ClrWrapper
2) P23.MetaTrader4.Manager.Contracts

Appreciate if you can assist me .

Regards
![mt4managerapi](https://user-images.githubusercontent.com/31030124/29306995-8339c572-81d2-11e7-957b-419df23d454b.jpg)

**Comment by Uriil** [comment]
Add missing using?

    using P23.MetaTrader4.Manager;

**Comment by kwiksys** [comment]
Thanks
