### ISSUE TITLE
MarginLevelGet return only code

### ISSUE THREAD

**Issue by nguyenchiencong** [Uriil/MetaTrader4.Manager.Wrapper#158]
MarginLevelGet only returns code and not MarginLevel.
Is it normal?

Thanks in advance

**Comment by Uriil** [comment]
No it's not. Do you use it in pumping mode?

**Comment by nguyenchiencong** [comment]
Hi,

Does it mean that It only return MarginLevel only when marginCall state?

Best

**Comment by nguyenchiencong** [comment]
Hi,

I figured it out. You actually have to add a 3rd argument with out as MarginLevel to get the MarginLevel back.

Thanks

**Comment by nguyenchiencong** [comment]
Sorry the problem isn't gone yet. MarginLevelGet returns the wrong result in MarginLevel. It return the MarginLevel on an entire different login user.

**Comment by nguyenchiencong** [comment]
For example:
Using id 90121879 and a group "example": 
I got this while using

```
MarginLevel mLevel;
var margin = metatrader.MarginLevelGet(login, group, out mLevel);
```

`{"Login":1911488268,"Group":" ô_","Leverage":1,"Updated":1913095168,"Balance":3.0942016143573606E-304,"Equity":5.69690297987583E-317,"Volume":0,"Margin":2.1529009768331841E+241,"MarginFree":1.097092171097607E+241,"Level":2.2745735436963693E-305,"MarginType":14780384,"LevelType":90121879}`

**Comment by nguyenchiencong** [comment]
Hi,

I can't share the MT credentials. But basically here is the code in pumping mode:

```
var login = 90121879;
var group = "example";
MarginLevel mLevel;
var margin = metatrader.MarginLevelGet(login, group, out mLevel);
```

Cheers

**Comment by Uriil** [comment]
For me it works as expected

**Comment by nguyenchiencong** [comment]
Nvm it's my fault. Thanks for helping.
