### ISSUE TITLE
Get all closed trades

### ISSUE THREAD

**Issue by tripathv** [Uriil/MetaTrader4.Manager.Wrapper#159]
Hi 

Not sure if this is the right forum or raising an issue is the right way but I was just wondering if there a way to get all the closed trades for a login?

**Comment by Uriil** [comment]
You can use methods `TradesUserHistory` or `AdmTradesRequest` (for this one provide Login as string instead of group, it's similar to MT4 Administrator logins search)

**Comment by tripathv** [comment]
Hi Uriil,

Thanks for the prompt response. I am trying to use the methods you suggested but in both cases, the count of trades is coming as 0. What am I missing?

I tried the AdmTradesRequest method first but no result so tried the history but still no luck.

  var are = new AutoResetEvent(false);
                using (var mt = new ClrWrapper(new ConnectionParameters
                {
                    Login = int.Parse(ConfigurationManager.AppSettings["LoginName"]),
                    Password = ConfigurationManager.AppSettings["Password"],
                    Server = ConfigurationManager.AppSettings["ServerAddress"]
                }))
                {
                    if (mt.IsConnected() > 0)
                    {
                        mt.PumpingSwitchEx(PumpingMode.Default);

                        mt.PumpingStarted += (sender, eventArgs) =>
                        {
                            are.Set();
                        };
                        are.WaitOne();
                        var allTrades = mt.TradesGet();
                        var allLogins = allTrades.Select(x => x.Login).Distinct();
                        var closedTrades = new List<TradeRecord>();
                        var dt = new DateTime(2000, 01, 01);
                        var dtTo =new DateTime(2017,08,21);
                        var from = uint.Parse((dt.ToUniversalTime().Subtract(new DateTime(1970, 1, 1))).TotalSeconds.ToString());
                        var to = uint.Parse((dtTo.ToUniversalTime().Subtract(new DateTime(1970, 1, 1))).TotalSeconds.ToString());
                        foreach (var login in allLogins)
                        {
                            var trades = mt.TradesUserHistory(login, from, to); //.AdmTradesRequest(login.ToString(), 0);
                            if (trades.Count > 0)
                            {
                                var cnt = trades.Count;
                            }

                        }

                       //Do something 
                    }
                }

**Comment by Uriil** [comment]
To use those methods you should not be in pumping mode

**Comment by tripathv** [comment]
Hi Uriil,

Thanks so I tried to be not in pumping mode but still not getting any records. 
 using (var mt = new ClrWrapper(new ConnectionParameters
                {
                    Login = int.Parse(ConfigurationManager.AppSettings["LoginName"]),
                    Password = ConfigurationManager.AppSettings["Password"],
                    Server = ConfigurationManager.AppSettings["ServerAddress"]
                }))
                {
                    if (mt.IsConnected() > 0)
                    {
                        var allTrades = mt.TradesRequest();
                        var allLogins = allTrades.Select(x => x.Login).Distinct();
                        var closedTrades = new List<TradeRecord>();
                        //var dt = new DateTime(2000, 01, 01);
                        //var dtTo =new DateTime(2017,08,21);
                        //var from = uint.Parse((dt.ToUniversalTime().Subtract(new DateTime(1970, 1, 1))).TotalSeconds.ToString());
                        //var to = uint.Parse((dtTo.ToUniversalTime().Subtract(new DateTime(1970, 1, 1))).TotalSeconds.ToString());
                        foreach (var login in allLogins)
                        {
                            var trades = mt.AdmTradesRequest(login.ToString(), 0);
                            //var trades = mt.TradesUserHistory(login, from, to); 
                            if (trades.Count > 0)
                            {
                                var cnt = trades.Count;
                            }

                        }

                     //Do something

**Comment by Uriil** [comment]
`AdmTradesRequest` requires full admin permissions. Do you have them? Can you request trades using MT4 Administrator?

**Comment by tripathv** [comment]
no I don't does TradesUserHistory also need admin access?

**Comment by Uriil** [comment]
Not sure, you need to check it in documentation

**Comment by tripathv** [comment]
All good.. TradesUserHistory did the job for me :)

Thanks
