### ISSUE TITLE
64 Bit

### ISSUE THREAD

**Issue by m-asgari** [Uriil/MetaTrader4.Manager.Wrapper#16]
Hello , 
  Could u Please let me know how can use it in windows 2012 base on 64bit 
is there any version to fix it I have got error on windows 2012

**Comment by Uriil** [comment]
Hi,
I run it on Windows server 2012 r2 x64 without any problem. What's the error?

**Comment by m-asgari** [comment]
could U please update the project with version support 64 bit because when I do it I have got many error from wrapper I will glad to do it Thanks

**Comment by Uriil** [comment]
I run exactly this version on x64

**Comment by Uriil** [comment]
Please install package via nuget and let me know, what's the problem

**Comment by m-asgari** [comment]
Thanks for your quick answer I just create a console app and try to run it but it has problem I know I have problem for that I ask u if possible for you create and console app that able to use it and we able to run and get some things like following :+1: 
            using (var mt = CreateWrapper())
            {
                mt.SymbolsRefresh();
                //without pumping, but depends on MT server settings
                var r = mt.TicksRequest(new TickRequest() { Symbol = "EURUSD", From = 0, To = int.MaxValue, Flags = (char)3 });
                Console.Write(r);
                var p = mt.PumpingSwitch((delegate(int i)
                {
                    //wait until 0 recieved, thats mean pumping started, and after 
                    //you will be able to recieve new quotes and access them
                }));
                //Assert.AreEqual(0, p);
                mt.SymbolAdd("EURUSD");
                Thread.Sleep(30000);
                var symbol = mt.SymbolInfoGet("EURUSD");

                Console.Write(symbol);
            }

**Comment by Uriil** [comment]
But I have some test written. 
You need to disable assembly signing and modify credentials and you will be able to run them

**Comment by m-asgari** [comment]
Yes I did it but have got error

**Comment by m-asgari** [comment]
I have got one note Dll size file P23.MetaTrader4.Manager.ClrWrapper.dll when I have got it from nuget it is 150 k but when I try to compile source code it will be 140 K

**Comment by Uriil** [comment]
Write me on Skype plz: uriil1987 I will try to help

**Comment by m-asgari** [comment]
my is m.asgari I try to  add you but it is not find i your id

**Comment by m-asgari** [comment]
I added you in skype

**Comment by Uriil** [comment]
Discussed. Just use latest version from develop branch
