### ISSUE TITLE
Retreive all open orders for a user and all users

### ISSUE THREAD

**Issue by kwiksys** [Uriil/MetaTrader4.Manager.Wrapper#160]
Appreciate if you can show how to retreive all open orders for the following :   

1) Single User
2) All Users

I am using C# .   Thank you.
Regards

**Comment by Uriil** [comment]
In non pumping mode:
- TradesRequest - use to get all open trades. Then you can filter them by user login,
- AdmTradesRequest - you can get all trades for user and then filter them to get open onec

In pumping mode:
- TradesGet
- TradesGetByLogin

**Comment by kwiksys** [comment]
Thanks.

I am new to the API.
Appreciate if I get a code on the pumping mode. Thank You.

**Comment by Uriil** [comment]
There are some tests in solution, which shows pumping mode usage

**Comment by kwiksys** [comment]
Thanks.

mt.AdmTradesRequest(string group, int OpenOnly);      

The above function call with parameters   - Group  and OpenOnly
What information to be input into this two fields  ?  

Regards

**Comment by Uriil** [comment]
for group pass login as string, for open only pass 1, as long as you need only open trades

**Comment by kwiksys** [comment]
Thanks for your assistance.

I tried to use  => mt.AdmTradesRequest("123455", 1); 
failed to reply and just hang there.
Could it be that the manager login has no full permission .
the other function call ->  •TradesRequest    has no issue.

Regards

**Comment by Uriil** [comment]
Yes, possibly it's permissions issue
