### ISSUE TITLE
Possible to auth user?

### ISSUE THREAD

**Issue by magick93** [Uriil/MetaTrader4.Manager.Wrapper#162]
Hi

I think I already know the answer - but wanted to double check.

I realize that the mt4 manager api needs a admin login, however is it also possible for trader user to authenticate using the api? Meaning, is there a method that takes a traders username and password and returns bool for authenticated?

Thanks

**Comment by Uriil** [comment]
No, it's not possible

**Comment by sysem85** [comment]
do you mean to use manager api to authenticate mt4 users ??
==> if yes, you may use UserPasswordCheck

**Comment by magick93** [comment]
> do you mean to use manager api to authenticate mt4 users ??
Yes, that is exactly what I mean! Thanks, this is perfect!
