### ISSUE TITLE
IsConnected problem

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#17]
Hi,

IsConnected() method returns always 0 (RET_OK) even if it is not connected.

**Comment by Uriil** [comment]
Hmm, strange. Actually I connect automatically in constructor, maybe that's what confused you? But below code returns result as expected

```
var client = new ClrWrapper(new ConnectionParameters() {
                Login = 0,
                Password = "",
                Server = ""
            });
var r = client.IsConnected();
Console.WriteLine(r);
client.Disconnect();
r = client.IsConnected();
Console.WriteLine(r);
```

**Comment by pantonis** [comment]
Check the below:

`  
var client = new ClrWrapper(new ConnectionParameters() {
                Login = 0,
                Password = " ",
                Server = " "
            });

            int isConnected1 = -1;
            isConnected1 = client.IsConnected();

            Console.WriteLine(isConnected1);

            int disResult = client.Disconnect();
            Console.WriteLine(disResult);

            int isConnected2 = -1;
            isConnected2 = client.IsConnected();

            Console.WriteLine(isConnected2);
`

isConnected2 shouldn't be returning 0 because 0 it means RET_OK.
After you disconnect it shouldn't be RET_OK (0) but RET_ERROR

**Comment by miho99** [comment]
Check the below:

`  
var client = new ClrWrapper(new ConnectionParameters() {
                Login = 0,
                Password = " ",
                Server = " "
            });

            int isConnected1 = -1;
            isConnected1 = client.IsConnected();

            Console.WriteLine(isConnected1);

            int disResult = client.Disconnect();
            Console.WriteLine(disResult);

            int isConnected2 = -1;
            isConnected2 = client.IsConnected();

            Console.WriteLine(isConnected2);
`

isConnected2 shouldn't be returning 0 because 0 it means RET_OK.
After you disconnect it shouldn't be RET_OK (0) but RET_ERROR

**Comment by Uriil** [comment]
Ok, you right, but from official documentation:

If connected, it returns non 0 value

**Comment by miho99** [comment]
Yes, agree you are right. Strange though because all requests return 0 if everything is OK. Wondering why they put it this way
