### ISSUE TITLE
Reconnect in Pumping Extended 

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#19]
Can you give an example of reconnection after a network or server problem in the Pumping Extended mode?

Thanks.

**Comment by Uriil** [comment]
Added example to wiki page: https://github.com/Uriil/MetaTrader4.Manager.Wrapper/wiki/Reconnect-in-pumping-mode

It works fine for me. In theory, instead of running separate task,  you can capture PumpingStopped event, but from my experience separate thread works perfect,

**Comment by nguyenchiencong** [comment]
Hi @Uriil , Is there an example of how you implement it?
Thanks

**Comment by Uriil** [comment]
Link in my previous post, what else do u need?

**Comment by nguyenchiencong** [comment]
Hi,

Sorry for being a noob. Just I don't know how to implement PumpingDataProvider as I'm new to C#.
An example of initialization of this class would help me a lot.

Thanks!

**Comment by Uriil** [comment]
Sorry, I don't have time for that. 

I suggest you to read some books or maybe watch videos

**Comment by nguyenchiencong** [comment]
It might be just me but I think throwing an example without any explanation is not helpful. The Interfaces you used are not documented and the exceptions handler come from where? That's just my 2 cents. Your answer seems very condescending.

**Comment by Uriil** [comment]
I am sorry if I harm you.

1. You don't need IPumpingDataProvider at all, or you can create your own
interface if needed

2. IMetaTraderCredentialsProvider has just single method which returns
credentials. Again, it is totally up to you how to implement it. U can get
them from config, environment, DB or any other source

3. HealthCheckException I missed it. However here you need to handle when
application fails to reconnect and crashed, in my case this never happened.
Probably u need to notify yourself by sending email.

**Comment by nguyenchiencong** [comment]
Thanks a lot! No harm done don't worry.

**Comment by nguyenchiencong** [comment]
Hi,
I have one more question. Where would you put the methods used be the wrapper in this case. Example:
`mt.TradeAdded` += (sender, record) =>

Thanks in advance
