### ISSUE TITLE
Wrapper dependency 

### ISSUE THREAD

**Issue by TradersSolutions** [Uriil/MetaTrader4.Manager.Wrapper#2]
Wrapper dependency 

I, can you tell me witch library need you wrapper in client post?
Cause, I can use your wrapper on my PC, but only this. Our team can’t start my application, one exception come without description (only system.io.file.filenotfound).

Many thanks for your job! 

**Comment by Uriil** [comment]
Most likely you missing msvcp*.dll or msvcr*.dll. Version depends on compilation configuration. Both can be found in system32 folder

**Comment by TradersSolutions** [comment]
Hi Uriil

I'm sorry, but, error persist

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	appliTest
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	559cded7
  Problem Signature 04:	appliTest
  Problem Signature 05:	1.0.0.0
  Problem Signature 06:	559cded7
  Problem Signature 07:	c2
  Problem Signature 08:	7
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	2057
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	a10f
  Additional Information 4:	a10ff7d2bb2516fdc753f9c34fc3b069

**Comment by TradersSolutions** [comment]
And, all requirement are installed (redistributable).
For example, if I install visual studio on client computer, it's work ... without, no :/

**Comment by Uriil** [comment]
You need visual c++ redistributable for x86 https://www.microsoft.com/en-us/download/details.aspx?id=46881 and mtmanapi.dll in specified location, that's all

**Comment by TradersSolutions** [comment]
Tank you UriiI

**Comment by TradersSolutions** [comment]
Hi UriiI;

My problem are fixed now.
It's because I've compile in "debug" mode, no on "release".

It's was my mistake, apologies for that
