### ISSUE TITLE
Pumping Events

### ISSUE THREAD

**Issue by mziadeh** [Uriil/MetaTrader4.Manager.Wrapper#20]
Hi,
is there any reason why the rest of pumping events not implemented? I need to be able to do something in case of symbols or groups update

**Comment by Uriil** [comment]
Not really, I just did not have enough to do it. But you are right, I should do it. I will try to do it on next weekend

**Comment by mziadeh** [comment]
Yeah that would be great.
thanks man

**Comment by Uriil** [comment]
Hi,
I've added new events to issue22 branch. Unfortunately I don't have admin access to MT server now, so I can not test it.

I will appreciate if you can test events: SymbolConfigurationUpdated, GroupConfigurationUpdated, RequestInfoUpdated, NewsTopicUpdated, NewNewsTopicUpdated, MailBoxUpdated

And let me know result of testing

**Comment by mziadeh** [comment]
Hi
Thanks for the update, I have tested them and they seems fine.

One last thing I've noticed in pumping users function, I think it should be the split as the pumping trades function as it also contains type (TRANS_ADD, TRANS_DELETE, TRANS_UPDATE).

**Comment by Uriil** [comment]
I can't find any example or documentation about distinguishing User events... not sure if it's possible and unfortunately don't have environment to test it

**Comment by miho99** [comment]
Yes tested them as well. Works like a charm. You can close this issue.
