### ISSUE TITLE
Question about thread safety

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#22]
Hi Uriil,

I have one question for you. 
Is the wrapper thread safe. I mean a manager can be access by two threads at the same time without any thread safety problems?

Thanks in advance.

**Comment by Uriil** [comment]
Wrapper is thread safe, but I am not sure about mtmanapi...

From my experience, you can safely use pumping  method concurrently, but I did not test the rest

**Comment by miho99** [comment]
What about the manager (direct) when creating users, trades etc...?

**Comment by Uriil** [comment]
That's what I am saying, never tried, so I don't know

**Comment by miho99** [comment]
I saw some strange error codes but it is random

**Comment by Uriil** [comment]
So probably it's not... I would not do that

**Comment by miho99** [comment]
Is there any way to look on manager (direct) in wrapper for thread safety issues?

**Comment by miho99** [comment]
e.g I was creating a deposit (TradeTransaction) and I got error code 255. This one does not exist in the Enum (Result codes)

**Comment by Uriil** [comment]
255 - Network problem, use method ErrorDescription to get details from error code.

Regarding thread safety, found official answer from Metaquotes: Pumping is thread safe, the rest is not

**Comment by miho99** [comment]
Thanks
