### ISSUE TITLE
cfgUpdateSymbolConfig error

### ISSUE THREAD

**Issue by sysem85** [Uriil/MetaTrader4.Manager.Wrapper#23]
I have successfully used the library to get the symbol config.

But when i update the symbol 's trade config (from full access mode to close access mode, and then back to full access mode) by cfgUpdateSymbolConfig. 

Although it can change the parameters successfully, the symbol cannot be traded after that no matter it is in full mode or not.

However, if i use c++ api directly, it does update the config successfully without error. I wonder whether i use the library correctly or not.

**Comment by Uriil** [comment]
Thank you for your feedback. Unfortunately I don't have access to mt server, and can not debug it. If you would be able to provide temporary acess to I would be glad to fix it

**Comment by Uriil** [comment]
Okay, you are right, it was bug, but it was related to entire cfgUpdateSymbolConfig function, not only updating trade mode. Due to bug, entire information about trade sessions were deleted.

Fixed, latest version uploaded
