### ISSUE TITLE
Logging Messages

### ISSUE THREAD

**Issue by m-asgari** [Uriil/MetaTrader4.Manager.Wrapper#24]
Hello , 
  Could you please let me know how to make Logging Messages for anything we will send and received from MT4 sever .

Regards
Sonny

**Comment by Uriil** [comment]
Could you please tell me, how FIX related to manager api?

**Comment by miho99** [comment]
@m-asgari  Can you explain what do you mean?

**Comment by m-asgari** [comment]
I means is How make logger in manager api for what we  send and received?

**Comment by Uriil** [comment]
But you send it directly to mt server? Or somehow via API?

**Comment by Uriil** [comment]
Manager api covers functionality, which supported by Mt manager and Mt administrator. If you can not do it via those two programs, you want be able to do it via API. In your case you will have to use some sort of Mt plugin, which is out of scope of this project

**Comment by miho99** [comment]
@m-asgari You mean every method call you make to MT4 server via Manager API?

**Comment by Uriil** [comment]
Closing issue, because unclear what is the problem
