### ISSUE TITLE
DateTime fields

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#26]
Hi,

How do I convert OpenTime, CloseTime of TradeRecord to DateTime and vice verca?

Thanks

**Comment by Uriil** [comment]
Please check this https://github.com/Uriil/MetaTrader4.Manager.Wrapper/wiki/Working-with-DateTime and let me know if it's clear or not

**Comment by miho99** [comment]
Thanks. Didn't know there was a wiki. I will also try to add content.
