### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#27]
Hi,

I experience unexpected crash of a .NET Windows service using the wrapper. I get this randomly. The service might be up for 10 hours but then it suddenly crashes. No dump file collected or exception. Only thing I see is the following entry in the windows event log:

Faulting application name: WindowsService1.exe, version: 1.0.0.0, time stamp: 0x571f5014
Faulting module name: mtmanapi64.dll, version: 4.0.0.950, time stamp: 0x001e2200
Exception code: 0xc0000409
Fault offset: 0x000000000003b7df
Faulting process ID: 0x3168
Faulting application start time: 0x01d19fae52a9fdfc
Faulting application path: C:\Services\WindowsService1\WindowsService1.exe
Faulting module path: C:\Services\WindowsService1\mtmanapi64.dll
Report ID: 2b881b00-48c4-4bbb-b80e-2c7b150cb748
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket , type 0
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: WindowsService1.exe
P2: 1.0.0.0
P3: 571f5014
P4: mtmanapi64.dll
P5: 4.0.0.950
P6: 001e2200
P7: 000000000003b7df
P8: c0000409
P9: 0000000000000005
P10: 

Attached files:
C:\Windows\Temp\WERD54C.tmp.appcompat.txt
C:\Windows\Temp\WERD55C.tmp.WERInternalMetadata.xml
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_WindowsService1._d260dfd168b9a58c9477a21f99e68bf7e3fedfae_5bdb08b3_cab_76acd56a\memory.hdmp
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_WindowsService1._d260dfd168b9a58c9477a21f99e68bf7e3fedfae_5bdb08b3_cab_76acd56a\triagedump.dmp

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_WindowsService1._d260dfd168b9a58c9477a21f99e68bf7e3fedfae_5bdb08b3_cab_76acd56a

Analysis symbol: 
Rechecking for solution: 0
Report ID: 2b881b00-48c4-4bbb-b80e-2c7b150cb748
Report Status: 4
Hashed bucket:

**Comment by Uriil** [comment]
I never used x64 version of Mt library, always was using x86, even on x64 machine. And it was working weeks without interruption.

First of all, can you confirm, that there is no memory leaks in your program?(memory consumption growes over time).

**Comment by miho99** [comment]
Something to do with the 64 bit version. I have used 32 bits and it seems to be ok.
