### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by petrallaf** [Uriil/MetaTrader4.Manager.Wrapper#28]
Hi,
this is my code:
var are = new AutoResetEvent(false);
                using (var metatrader = new ClrWrapper(new ConnectionParameters
                {
                    Login = _login,
                    Password = _password,
                    Server = _server
                }))
                {
                    metatrader.PumpingSwitch(i =>
                    {
                        if (i == 0) // 0 - means pumping started
                            are.Set();
                    });

                    are.WaitOne();

                    IList<UserRecord> users = metatrader.UsersGet();
                }

_login is int, _password is string and _server is string formed as "xxx.xxx.xxx.xxx:443"

_login, _password and _server are correct parameters but I have "Failed to login to server" error. 

Can you help me?
Thank you

**Comment by Uriil** [comment]
Do you use manager account or trader?

**Comment by petrallaf** [comment]
Yes I use my manager account.
Is MT4 manager mtmanapi.dll? If yes, I use it.
Thank you

**Comment by Uriil** [comment]
This API works only with manager accounts

**Comment by petrallaf** [comment]
Oh I'm sorry.
Thank you for all
