### ISSUE TITLE
TradesUserHistory returns no trade

### ISSUE THREAD

**Issue by atjozi** [Uriil/MetaTrader4.Manager.Wrapper#34]
HI,

I am using following code in visual studio 2015:

`IList<TradeRecord> trades = metatrader.TradesUserHistory(xxxx, 0, UInt32.MaxValue);`

and i get 0 records for user that has some records in MT4Manager. Method UserRequest works fine for me and i receive some values, which I guess means that I've connected as expected

Thank you in advance for answer
Jovana

**Comment by Uriil** [comment]
Hi,
Could you please try 1465948800(tomorrow) and (UInt32)int.MaxValue as upper boundary

**Comment by atjozi** [comment]
Hi,
Thank you for quick reply, but I still receive 0 trades

Thanks

**Comment by Uriil** [comment]
Might sound strange, but does your account has CLOSED trades?

There is TradesUserHistoryTests and it passes for me correctly, just checked it

**Comment by atjozi** [comment]
Hi,
Thank you very much, I was able to retrieve closed trades for an account with expected results. However, I am still not sure how can open trades be retrieved. I have already tried `TradesGetByLogin` with having 0 results, instead of expected 1 result. can you please point me in the right direction?

Thanks!

**Comment by Uriil** [comment]
You can use AdmTradesRequest(provide login as string to first parameter) or TradesGet* methods, but they require pumping connection
