### ISSUE TITLE
how to get the symbols for each security

### ISSUE THREAD

**Issue by Tinanuaa** [Uriil/MetaTrader4.Manager.Wrapper#35]
Hi,

Is there an interface that can get the symbol for each security? Any help would be appreciated!

**Comment by Uriil** [comment]
Hi,

not directly. You need to:
1) get all symbols(CfgRequestSymbol)
2) get all securities(CfgRequestSymbolGroup)
3) map securities to their appropriate index in array
4) filter symbols by required security(property Type)

**Comment by Tinanuaa** [comment]
Thank you very much! Just to make sure, all the methods started with cfg is for admin? If I use SymbolsgetAll to get all the symbol, and SymbolsGroupsGet to get all the securities, should the result be same as yours? Cause I only have manager account, and when I use methods started with cfg, it has exception or return 0 data.

**Comment by Tinanuaa** [comment]
Another question is the Type(property) in symbol is the index of the corresponding SymbolGroup in the Symbolgroup List ,right?And groupSecurity of a group has the same order as the list of SymbolGroup?  In fact , I want to get the security settings for a specific group and symbol. And I want to find the corresponding groupSecurity of a specific group with the specific symbol. Hope you can get what I mean.

**Comment by Uriil** [comment]
Result should be the same, but I did not use those methods, so can not confirm it.

And order should be same as well

**Comment by Tinanuaa** [comment]
Thank you!
