### ISSUE TITLE
SecMargin not updating on Group level 

### ISSUE THREAD

**Issue by nazakli** [Uriil/MetaTrader4.Manager.Wrapper#36]
Hi, 

Group Security margin list not updating correctly. there is a copy and past error on 

ConversionHelper.Cpp 
Line 825 : Replaced with following lines. 

```
for (int i = 0; i < configuration->SecGroups->Count; i++)
		newConfiguration->secgroups[i] = *Convert(configuration->SecGroups[i]);
		
	for (int i = 0; i < configuration->SecMargins->Count; i++)
		newConfiguration->secmargins[i] = *Convert(configuration->SecMargins[i]);
```

**Comment by Uriil** [comment]
Hi,

Thank you. I will fix it until end of this week

**Comment by Uriil** [comment]
Okay, i fixed it and updated nuget package. Please check and let me know, if everything okay

**Comment by nazakli** [comment]
Hi Uriil, 

I have created a fresh project and updated nuget package. 

When I start to my application receiving following error code. 

> System.IO.FileLoadException was unhandled
Message: An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'P23.MetaTrader4.Manager.ClrWrapper, Version=0.1.2.3, Culture=neutral, PublicKeyToken=e4252536f12a7833' or one of its dependencies. **Strong name validation failed**. (Exception from HRESULT: 0x8013141A)


```
ConnectionParameters conParams = new ConnectionParameters();
conParams.Login = 1072;
conParams.Password = "PassWord1234";
conParams.Server = "127.0.0.1";
ClrWrapper mt = new ClrWrapper(conParams);
mt.PumpingSwitchEx();

IList<Group> __grpList = mt.CfgRequestGroup();
Group flx = __grpList.Single(x => x.Name == "Test");
 // Without any change
mt.CfgUpdateGroup(flx);
```

**Comment by Uriil** [comment]
Oh sorry, got problems with certificate password, it was not set, but VS did not rise error.

Please try once again

**Comment by nazakli** [comment]
Hi Uriil, 

I updated with nuget and same error occurs again. 
```
System.IO.FileLoadException was unhandled
Message: An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'P23.MetaTrader4.Manager.ClrWrapper, Version=0.1.2.3, Culture=neutral, PublicKeyToken=e4252536f12a7833' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

**Comment by Uriil** [comment]
Ok, finally it's fixed. Signing has broken after I reinstalled my machine.

**Comment by nazakli** [comment]
Hi Uriil,, 

Yes It worked. also made one test for SecMargin setup and works fine too.. 

Thank you,
