### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#37]
Hi.

I downloaded the source code build successfully and tried to run the tests.
I get 

![image](https://cloud.githubusercontent.com/assets/18263849/16412835/ff857482-3d36-11e6-8fce-b9bebc639e5e.png)

**Comment by Uriil** [comment]
Disable signing for both assemblies

**Comment by miho99** [comment]
I already did it.

**Comment by Uriil** [comment]
Build all dependencies one by one

**Comment by miho99** [comment]
I did everything builds successfully
even If I create another project and add the wrapper library it builds successfully. As soon as I run it it gives the same error

**Comment by Uriil** [comment]
Just to make sure.

Can you install nuget package and check if it's working for you?

**Comment by pantonis** [comment]
yes it is working with nuget. What about the source?

**Comment by miho99** [comment]
Yes it is working with nuget. What about the source? Why it is not working?

**Comment by Uriil** [comment]
I just cloned it to new machine,

Disabled signing for P23.MetaTrader4.Manager.Contracts
Disabled signing for P23.MetaTrader4.Manager.ClrWrapper
And build P23.MetaTrader4.Manager.Tests without any error.

*Make sure build configuration set to x86

**Comment by miho99** [comment]
I did but I am still receiving the same error. :(

I have uploaded the code into this repository:

https://github.com/miho99/MT4Test

Run the console app and check the error.

Thanks

**Comment by Uriil** [comment]
Okay, I've changed build configuration to x86 and started it.

Exception was about connection to MT server, which is expected

**Comment by miho99** [comment]
Strange. 

Do you know what might be causing me this issue?

**Comment by Uriil** [comment]
Unfortunately no... since I can't reproduce it, I can't help

**Comment by Uriil** [comment]
Can you setup some virtual machine, reproduce error and share access with me?

**Comment by miho99** [comment]
problem was fixed. most probably something with my visual studio after updating to the new vs2015 update 3. I reinstalled it and now everything is ok.

Thanks for the support.
