### ISSUE TITLE
Need Help to Use this...!

### ISSUE THREAD

**Issue by bhuvaneshfx** [Uriil/MetaTrader4.Manager.Wrapper#38]
I am new here... I need help to communicate with MT4 manager using this wrapper... Please someone explain me in Step by step...! ThankYou...!!! :)

**Comment by Uriil** [comment]
Please find example below: 

    using (var metatrader = new ClrWrapper(new ConnectionParameters
            {
                Login = 123456,
                Password = "managerPassword",
                Server = "123.123.123.123:443"
            }))
    {
        IList<UserRecord> users = metatrader.UsersRequest();
    }

**Comment by bhuvaneshfx** [comment]
Uriil, Thankyou for your immediate response...! Can you explain how to run this package...?

**Comment by Uriil** [comment]
Install it from nuget: Install-Package MetaTrader4.Manager.Wrapper

It will add reference to your solution and you will be able to use it.

It's not independent software, it's library, which allows to communicate with MT4 from .NET application

**Comment by bhuvaneshfx** [comment]
Can i get any sample program to communicate with MT4 manager from .NET application using this library...?

**Comment by Uriil** [comment]
Please write me on skype: uriil1987

**Comment by Uriil** [comment]
Discussed privatly

**Comment by nguyenchiencong** [comment]
Hi @Uriil Can you share on how to run the code snippet? Thanks

**Comment by Uriil** [comment]
Hi @nguyenchiencong you will need Visual Studio and basic knowledge of .NET and Nuget

**Comment by nguyenchiencong** [comment]
Thanks. Made it work.
