### ISSUE TITLE
do have x64 version?

### ISSUE THREAD

**Issue by liufajian** [Uriil/MetaTrader4.Manager.Wrapper#39]
excuse me, i prefer to x64,but i can not compile the project succesfully,so do you have a plan to release x64 dll,thanks

**Comment by Uriil** [comment]
Hi,
What's the error during compilation?

**Comment by liufajian** [comment]
hi, i have compile successfully, by removing snk, set up win10 sdk,and then change afxres.h to winres.h. I am ready to use the compiled dll, if i meet problem , i will report to you,thanks!

**Comment by liufajian** [comment]
ok，i have reference the dll, and got 'bad image' error, so i have to admit that i am only familiar with c#, i discard to research how to compile x64 dll ...

**Comment by Uriil** [comment]
Unfortunately I don't have time to investigate this topic now. Maybe some when in future

**Comment by miho99** [comment]
@liufajian 

1. Check that your solution configuration that targets x64.
2. Right click your project => properties => build tab and uncheck option "Prefer 32-bit".

Clean, Build and run

**Comment by Greatsamps** [comment]
a 64-bit version of the nuget would be a nice to have ...

**Comment by pantonis** [comment]
@Greatsamps it is a good idea but if you follow the steps above that @miho99 posted you should be fine

**Comment by Greatsamps** [comment]
Yeah it's not a problem, just me being lazy and it being easy to do a nuget update rather than recompile!

**Comment by Uriil** [comment]
Ok, once I will have time,I will investigate this topic. Here is link to [documentation:](https://docs.nuget.org/create/uwp-create#native-light-up)

**Comment by hisvarlar** [comment]
Hello, 

I have same problem. When I publish my web application on IIS gives an error.

**System.BadImageFormatException: Could not load file or assembly 'P23.MetaTrader4.Manager.Clr Wrapper' or one of its dependencies. An attempt was made to load a program with an incorrect format.**

I tried x86 and x64 mode build but got same error. Also tried to add references manuelly but doesnt work same as download from Nuget.

**Comment by Greatsamps** [comment]
With that IIS issue, you need to specify a specific folder for the MT4Manager dll's, as otherwise windows will be looking in the system folder for them. we have created a specific folder for the on the server, you can pass this path to mt4man.dll in the constructor to the wrapper which does the trick.

**Comment by Uriil** [comment]
**System.BadImageFormatException: Could not load file or assembly 'P23.MetaTrader4.Manager.Clr Wrapper' or one of its dependencies. An attempt was made to load a program with an incorrect format.**

To use x86 version, you need to setup property "Enable 32bit applicaiton" to true in IIS settings.

If you can't run it as console application, you missing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145), again version x86.

To use x64, you will have to rebuild project with x64, it's not included in nuget package

**Comment by hisvarlar** [comment]
Thanks, It works.

**Comment by sadro** [comment]
I have same problem.
I am using Visual Studio 2013 and IISExpress. 
I configured debug x86 but error continous. I have publish web site to IIS and configured application pool framework 4.0 Integrated, Enable 32 Bit (True) but still the same. all c++ redistrubutes are installed (2008 (x86 - 64Bit), 2010 (x86) 2012 (x86 - 64Bit), 2013 (x86 - 64Bit), 2015 (x86 - 64Bit).

Could not load file or assembly 'P23.MetaTrader4.Manager.ClrWrapper.DLL' or one of its dependencies. The specified module could not be found.

**Comment by Uriil** [comment]
Sadro,

Steps I mentioned above are the only dependencies.  I was installing it to fresh windows servers many times, and I am pretty sure, that there are no other dependencies.

However, if you will provide me access to your server I can check it for you

**Comment by sadro** [comment]
Hi Uriil,
Can you give me your mail or skype address. I need to contact you private for connect our server info.

**Comment by Uriil** [comment]
Skype: uriil1987

**Comment by sadro** [comment]
I send you request from skype. skype: boraerel

**Comment by Uriil** [comment]
I am not using x64 version and won't be able to help you

**Comment by miho99** [comment]
Did you install the Microsoft Visual C++ x64 Redistributable?

Also What errors do you get?

**Comment by avibb** [comment]
Thanks for the response, I installed it.
I get the known error:
**System.BadImageFormatException: Could not load file or assembly 'P23.MetaTrader4.Manager.ClrWrapper, Version = 0.3.6218.37690, Culture = neutral, PublicKeyToken = E4252536f12a7833 or one of its dependencies. An attempt was made to load a program with an incorrect format.**

**Comment by miho99** [comment]
This mean incorrect build settings.
1. Check that your solution configuration targets x64.
2. Right click your project => properties => build tab and uncheck option "Prefer 32-bit".

**Comment by fabry1** [comment]
I'm tryng to familiarize with P23.MetaTrader4.Manager.ClrWrapper and using same credentials of MT4
i get an Error during instancing ClrWrapper: 
mt = new ClrWrapper(conParam) => Failed to instantiate manager instance
Which set up is required?

**Comment by Uriil** [comment]
@fabry1 how your question related to this topic?

**Comment by fabry1** [comment]
Sorry if wrong topic, at moment I do not know if related to x64 or other settings.
Please guide me to proper usage of topics and P23.MetaTrader4.Manager.ClrWrapper to solve the issue. Many thanks in advance Uriil.
