### ISSUE TITLE
Credit In

### ISSUE THREAD

**Issue by prodipgogoi** [Uriil/MetaTrader4.Manager.Wrapper#41]
For CreditIn i am getting result 3. That is invalid data. CreditOut is working fine for me.

`TradeTransInfo trade = new TradeTransInfo();
            trade.Cmd = TradeCommand.Credit;
            trade.OrderBy = Convert.ToInt32(parameters["login"]);
            trade.Price = Convert.ToDouble(parameters["amount"]);
            trade.Comment = parameters["comment"];
            trade.Type = TradeTransactionType.BrBalance;
ClrWrapper wrapper = Proxy.CreateWrapper.GetWrapper();
int result=wrapper.TradeTransaction(trade);`
return result =3 in my case.

**Comment by Uriil** [comment]
Hi what do you mean by CreditIn and CreditOut? Deposit and Withdrawal?

And the only thing you change is amount(Price)?

**Comment by prodipgogoi** [comment]
I made a mistake on uploading this code. I am using Credit command. in that I can do credit out, but not credit in. the only difference in both is just the amount. for credit in I use 1 and for credit out I use -1. 

Balance and withdrawal are working perfectly.

**Comment by Uriil** [comment]
I never used credit operation. However, could you try to set Expiration to some positive number

**Comment by prodipgogoi** [comment]
Its work's. Thanks a lot.

**Comment by k7zj** [comment]
A same problem happen in my code.
I set Expiration to different positive number , but it returns result=3 anyway.
Balance and withdrawal are working perfectly.
