### ISSUE TITLE
Callback handler allocation

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#42]
Hi. In PumpingExtended.cpp

this should not throw exception but instead freed

```
if (_callBackHandler.IsAllocated)
		throw gcnew MetaTrader4::Manager::Contracts::MetaTraderException("Callback handler alread allocated");
```
should be

```
if (_callBackHandler.IsAllocated)
	{
		_callBackHandler.Free();
	}
```

In case the pumping manager is disconnected existing manager can be used to reconnect and this prevents it.

**Comment by Uriil** [comment]
Did you check, that re connection works? I think I was trying to reconnect previously, but ended up with disposing manager interfaces completely, and creating new instance

**Comment by miho99** [comment]
if disconnection occurs pumping stopped is fired. Instead for disposing and creating new instances (expensive operation) existing manager can be reconnected. If the code above is changed it works perfectly.

**Comment by Uriil** [comment]
Okay, I will apply it on weekend

**Comment by miho99** [comment]
ok thanks

**Comment by Uriil** [comment]
Ok, I've implemented it and pushed new version to nuget, please verify and confirm that everything correct

**Comment by miho99** [comment]
Excellent. Eveything is ok. 

Thanks

**Comment by pantonis** [comment]
btw can you merge into master?

**Comment by miho99** [comment]
Can you merge code into master?

**Comment by Uriil** [comment]
done

**Comment by Uriil** [comment]
Can you reproduce it on small piece of code?
