### ISSUE TITLE
MetaTrader4.Manager.Wrapper asp.net MVC

### ISSUE THREAD

**Issue by arehman2001** [Uriil/MetaTrader4.Manager.Wrapper#43]
Hello
Is there any sample code for MetaTrader4.Manager.Wrapper in asp.net/MVC, I would appreciate if some one can send me any code, I am new to both MetaTrader4.Manager.Wrapper and asp.net/mvc.

Thanks in anticipation

**Comment by pantonis** [comment]
Accessing the platform directly from the web project it is not the best idea in terms of security!

**Comment by Uriil** [comment]
This is out of scope of this project
