### ISSUE TITLE
PumpingSwitchEx flags implementation

### ISSUE THREAD

**Issue by pantonis** [Uriil/MetaTrader4.Manager.Wrapper#46]
Hi.

I have implemented PumpingSwitchEx flags. Can you contact me on gitter to discuss how to commit it?

Thanks.

**Comment by Uriil** [comment]
Fork this repo. and create pull request. I will review and merge it everything ok

**Comment by pantonis** [comment]
OK just did it

**Comment by Uriil** [comment]
I think in your fork, you pointed to your branch. 

What you need to do, is point to my develop

**Comment by Uriil** [comment]
Ok, I think I've managed to do it

**Comment by pantonis** [comment]
ok perfect can you merge to master please?

**Comment by Uriil** [comment]
Done, but I renamed enum and parameter.

Pushed latest to nuget

**Comment by pantonis** [comment]
Perfect.
Is it possible to remove assembly signing staff as it is difficult to make changes to code. I had to remove it, change the code, build, test and then  revert and do the changes manually.

I think this is not needed :)

**Comment by Uriil** [comment]
I know some teams upload it GAC, so it has to be signed... And will prefer to keep it this way

**Comment by pantonis** [comment]
ok

**Comment by pantonis** [comment]
ok

**Comment by pantonis** [comment]
Can you merge develop into master. I think you missed minor last commit (renamed variable pumpingFlag -> pumpingMode)

**Comment by Uriil** [comment]
done
