### ISSUE TITLE
every time got RET_BAD_ACCOUNT_INFO

### ISSUE THREAD

**Issue by bilal580** [Uriil/MetaTrader4.Manager.Wrapper#5]
Hi
i am trying to use you wrapper but when every i try to connect every time  _manager->Manager->Login(connectionParameters->Login, password) function return error code 65 would you please tell me how to fix this issue 

i am trying to connect using following code 
  using (var mt = new ClrWrapper(new ConnectionParameters
            {
                Login = 120034822,
                Password = "p4ufzwj",
                Server = "38.76.18.20:443"
            },
                @"C:\MetaTrader4.Manager\MetaTrader4.Manager.Wrapper-master\src\Libraries\mtmanapi\mtmanapi.dll"))

**Comment by Uriil** [comment]
That's manager API, and your account must be manager. 65 mean you trying to connect using regular acount

**Comment by bilal580** [comment]
thanks for reply is there any API for connect with regular acccount

**Comment by Uriil** [comment]
I don't know
