### ISSUE TITLE
New version of Manager API

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#51]
If I send you the new version of Manager API can you update the project?

Thanks

**Comment by Uriil** [comment]
I have access to it. No need to send. I will try to do it on weekend

**Comment by Uriil** [comment]
Not sure why, but latest version of API does not work for me. This `m_manager=m_factory.Create(ManAPIVersion))` method returns NULL.

And I've checked it on MetaQuotes example also : ManagerAPITrade And I see same issue.

Maybe you can ask about it on their forum?

**Comment by Uriil** [comment]
And moreover, I don't see any benefits of upgrading. The only change I see, that they renamed one method

**Comment by miho99** [comment]
What version is the .h file you have?

**Comment by Uriil** [comment]
I was checking 985

**Comment by miho99** [comment]
I ran the example and it works fine. I even updated the wrapper and it runs fine again with 985. One mistake I did initially and got the error was to not replace the .h file in the project. Maybe is that

**Comment by Uriil** [comment]
Still have same problem for both libs x86 and x64.

This line returns NULL: Manager = Factory.Create(ManAPIVersion)

**Comment by Uriil** [comment]
And just checked on fresh VM, same problem.

Maybe you will send me your updated version with all DLLs and I will check it on my side?

**Comment by miho99** [comment]
I have a new package for the 985. Let me know when you download it in order to remove it

[Download](https://drive.google.com/open?id=0B-dic8zDHCwKaWJnNHVFV1R1OVU)

**Comment by Uriil** [comment]
downloaded

**Comment by Uriil** [comment]
Strange... I had exactly same version but mine did not work for me...

Pushed nuget package with latest version, let me know if everything correct

**Comment by miho99** [comment]
everything about MQ is strange :)

**Comment by miho99** [comment]
It seems ok can you merge into master please?

**Comment by Uriil** [comment]
done

**Comment by miho99** [comment]
Great. Thanks.
