### ISSUE TITLE
Trade transactions, error 3, invalid parameters

### ISSUE THREAD

**Issue by philvv** [Uriil/MetaTrader4.Manager.Wrapper#52]
Hi Uriil, 

Been playing with your wrapper, great work! Been able to login, receive pumping notifications perfectly but I am stuck on something odd.. Trade transactions.

I can do any of the Br* tranascations ok. So broker open trade, broker deposit etc. but any of the client versions return error 3, invalid parameters

Example:
var tti = new TradeTransInfo
                {
                    Cmd = TradeCommand.Sell,
                    OrderBy = 900,
                    Comment = "API test",
                    Symbol = "EURUSD",
                    Price = 1.10223,
                    Volume = 100,
                    Type = TradeTransactionType.OrderMkOpen
                };

On the mt4 manager log, I see error for 'unknown trade transaction'. Have you ever encountered this?

Im sure I'm being stupid but I have tried lots of code combos, but no joy with client trade trasnactions.

Many thanks,
Phil

**Comment by Uriil** [comment]
Unfortunately, manager api allows only Broker transactions, other exist only for events in pumping mode

**Comment by philvv** [comment]
I sort of guessed that.. makes sense now. Thank you for clarifying.
