### ISSUE TITLE
how to login in hyt4demoeu.hyinvestment.com:443?

### ISSUE THREAD

**Issue by pigvip** [Uriil/MetaTrader4.Manager.Wrapper#53]
i am try lost.log message.

0	2016.07.28 17:40:30.285		MetaTrader 4 Manager API build 950 initialized
0	2016.07.28 17:40:30.718	hyt4demoeu.hyinvestment.com:443	Connect
65	2016.07.28 17:40:48.135	hyt4demoeu.hyinvestment.com:443	'2010239657': login failed (Invalid account)
0	2016.07.28 17:40:48.136		Remove: manager 6B7AF8

**Comment by Uriil** [comment]
Your account does not look like a manager one. Do you have required permisions?

**Comment by Uriil** [comment]
Closing, because there is no response
