### ISSUE TITLE
ReportsRequest problem

### ISSUE THREAD

**Issue by miho99** [Uriil/MetaTrader4.Manager.Wrapper#54]
I am calling ReportsRequest and I get strange behavior most of the times.
I can see on the MT4 journal my request which returns some data

![image](https://cloud.githubusercontent.com/assets/18263849/17286129/16bcfd7e-57d0-11e6-9bd2-93ad098fafbd.png)

But on the app I don't get these data.
After the following line is executed total variable is 0

TradeRecord\* records = _manager->Manager->ReportsRequest(convertedRequest, Convert(logins), &total);

**Comment by Uriil** [comment]
Please show he content of convertedRequest. I am using this method for about a year and have not noticed any glitches

**Comment by Uriil** [comment]
Checked once again, and everything correct on my side. Will you be able to provide me temporary account to view this issue on my side?

**Comment by Uriil** [comment]
Did you figure out what was the problem?

**Comment by miho99** [comment]
No I didn't figure.

**Comment by miho99** [comment]
Maybe this is related to [#59](https://github.com/Uriil/MetaTrader4.Manager.Wrapper/issues/59)

**Comment by Uriil** [comment]
Can not reproduce
