### ISSUE TITLE
Conversion Rates on TradeRecord 

### ISSUE THREAD

**Issue by nazakli** [Uriil/MetaTrader4.Manager.Wrapper#55]
Hi Uri, 

I found a new bug in AdmTradeRecordModify command. As you can see following entry commission agent overwrites conv rates value. 

ConversionHelpers.cpp
`1527: 	output->conv_rates[0] = input->CommissionAgent;`
`1528:	output->conv_rates[1] = input->CommissionAgent;`

Thank you,

**Comment by nazakli** [comment]
Hi Uriil, 

I solved issue with following code but needs to be confirmed. 
```
1527: output->conv_rates[0] = input->ConvRates[0];
1528: output->conv_rates[1] = input->ConvRates[1];
```

**Comment by Uriil** [comment]
Thank you for your report. I will try to fix it as soon as possible

**Comment by Uriil** [comment]
Fixed and published nuget package.

Please verify and let me know, if everything correct

**Comment by nazakli** [comment]
hi Urill 
I tested and working fine. Also I have found a new bug about api_data section. It's not updating by conversion. as you know there is an array with 4 element. 

I added following code to and needs to be confirmed. 

Current API structure 
```
TradeRecord->api_data values. 
 int               api_data[4];      // for api usage
```
TradeRecord.cs -> Adding this line to C# code in Contracts namespace

```
162:  /// <summary>
163:  /// API Integer data array for internal usage.
164: /// </summary>
165: public IList<int> APIData { get; set; }
```
ConversionHelpers.cpp
```
1508: output->APIData->Add(input->api_data[0]);
1509: output->APIData->Add(input->api_data[1]);
1510: output->APIData->Add(input->api_data[2]);
1511: output->APIData->Add(input->api_data[3]);

... 
1563: output->api_data[0] = (int)input->APIData[0];
1564: output->api_data[1] = (int)input->APIData[1];
1565: output->api_data[2] = (int)input->APIData[2];
1566: output->api_data[3] = (int)input->APIData[3];

```

**Comment by Uriil** [comment]
Pushed changes, please let me know if now everything okay

**Comment by nazakli** [comment]
Thank you Uriil, works fine.
