### ISSUE TITLE
problem with order update

### ISSUE THREAD

**Issue by prodipgogoi** [Uriil/MetaTrader4.Manager.Wrapper#57]
i am getting a result 3 from following code. please help
ClrWrapper2 wrapper = Proxy.CreateWrapper.GetWrapper();
                    try
                    {
                        if (wrapper != null)
                        {
                            TradeRecord trecord = ProxyTradeOperations.proxyOrderGet(ticket, wrapper);
                            if (trecord != null)
                            {
                                TradeTransInfo info = new TradeTransInfo();
                                info.Order = ticket;
                                info.Type = TradeTransactionType.OrderModify;
                                info.Price = trecord.OpenPrice;
                                info.Sl = trecord.Sl;
                                info.Tp = trecord.Tp;
                                info.Volume = trecord.Volume;
                                info.OrderBy = trecord.Login;
                                info.Comment = trecord.Comment;
                                info.Symbol = trecord.Symbol;
                                uint timestamp = CommonMethods.DateTimeToUnix(DateTime.Now.AddDays(2));
                                info.Expiration = timestamp;
                                if (parameters.ContainsKey("tp"))
                                {
                                    info.Tp = Convert.ToDouble(parameters["tp"]);
                                }
                                if (parameters.ContainsKey("sl"))
                                {
                                    info.Sl = Convert.ToDouble(parameters["sl"]);
                                }
                                if (parameters.ContainsKey("comment"))
                                {
                                    info.Comment = parameters["comment"];
                                }
                                if (parameters.ContainsKey("price"))
                                {
                                    info.Price = Convert.ToDouble(parameters["price"]);
                                }
                                resp.Result = wrapper.TradeTransaction(info);
                            }
                            Proxy.CreateWrapper.close(wrapper);
                        }
                    }
                    catch (Exception)
                    {
                        Proxy.CreateWrapper.close(wrapper);
                    }

**Comment by Uriil** [comment]
You can use only broker transactions with API, the ones which starts with "Br"

And as far as I remember Cmd is also mandatory parameter

**Comment by prodipgogoi** [comment]
finally i used AdmTradeRecordModify method and it working fine but for this i need admin permission.
