### ISSUE TITLE
using DailyReportsRequest to get the daily report for a login but returns 0

### ISSUE THREAD

**Issue by Tinanuaa** [Uriil/MetaTrader4.Manager.Wrapper#62]
Hi Uriil,

I want to use the DailyReportsRequest to request the daily report for a login but it returns 0 all the time. following is my code ,is there any problem I didn't notice? Any help would be appreciated!

IList<DailyReport> daily_history;
DateTime day_from = new DateTime(2016, 7, 1);
DateTime day_to = new DateTime(2016, 7, 31);
using (var mt = initialHelpers.CreateWrapper())
 {
         daily_history = mt.DailyReportsRequest(new DailyGroupRequest() { From = Extract.ToUnixTime(day_from), Name = "group_name", To = Extract.ToUnixTime(day_to) }, new List<int> { 1});
 }
Best reagrds,

Tina

**Comment by Uriil** [comment]
Hi,

At first glance it looks good. First step to verify, can you connect to MT using MT Manager and request for reports exactly with the same parameters

**Comment by Tinanuaa** [comment]
Hi,

I can connect to MT using MT Manager and get groups, symbols , trades, but not report. I also tried ReportsRequest but it still returns a list with zero member. And I am sure this login has trades in July. Besides, I cannot get trades with TradesUserHistory,TradesRequest but I can get trades with AdmTradesRequest and I don't need to start pumping mode, as you have mentioned in another issue that we need to start pumping mode to use AdmTradesRequest .

**Comment by Tinanuaa** [comment]
Hi,
 
I've found the problem, I used the wrong login, sorry about that and thank you for your time ! And I want to make sure whether it's right to turn on pumping mode using the following code? Cause even if I turned on pumping mode, I can still request nothing from TradesGetByLogin

static public void pumpingCallBack(int i)
{
     Console.WriteLine("Turn into pumping mode!");
}
static public int startPumping(ClrWrapper mt)
{
       PumpingCallbackDelegate dele = pumpingCallBack;
       return mt.PumpingSwitch(dele);
 }

public void getData()
{
using (var mt = initialHelpers.CreateWrapper(parameters))
 {
         startPumping(mt);
         trades = mt.TradesGetByLogin(1, "group_name");
}
}

**Comment by Uriil** [comment]
Pumping is mandatory for methods, which contains *Get in their name

**Comment by Tinanuaa** [comment]
Ok, but I have turned it on and still cannot get trades using TradesGetByLogin,so I want to check whether my code can turn on pumping mode correctly?

**Comment by Uriil** [comment]
You have a problem in it, pumping requires some to time to start and you are not waiting for it. Please check example: Using wrapper in Pumping mode on main page

**Comment by Tinanuaa** [comment]
Thank you ,I  understand!
