### ISSUE TITLE
I want to get daily reports. How to get the daily report in pumping Switch mode.

### ISSUE THREAD

**Issue by ranahamid** [Uriil/MetaTrader4.Manager.Wrapper#63]
``

        /// <summary>
        /// Switch into pumping mode
        /// delegate will be invoked on any pumping event
        /// </summary>
        private void PumpingSwitch()
        {
            if (switchFlag == false)
            {
                var are = new AutoResetEvent(false);
                clrWrapper.PumpingSwitch(i =>
                    {
                        if (i == 0) // 0 - means pumping started
                        are.Set();
                    });

                are.WaitOne();
                switchFlag = true;
            }
        }

        /// <summary>
        /// Need To do work.TO BE
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void RequestButton_DailyReportsClick(object sender, EventArgs e)
        {
            if (clrWrapper.IsConnected() != 0)
            {
                int login;
                LogIn();
                //User Request
                PumpingSwitch();
                IList<UserRecord> tradeRecords = clrWrapper.UsersGet();
                IList<int> listLogin=new List<int>();

                foreach (var p in tradeRecords)
                {
                    login = p.Login;
                    listLogin.Add(login);
                }
             
       

                
                DailyGroupRequest request = new DailyGroupRequest();
                request.To = ToUnixTime(System.DateTime.Now);
                request.From = ToUnixTime(System.DateTime.Now.AddDays(-11120));
                request.Name = "Daily"; //NEED TO EDIT-----------

                IList<DailyReport> dailyReportses = clrWrapper.DailyReportsRequest(request, listLogin);
                IList<DailyReportFxtf> list = new List<DailyReportFxtf>();
                int i = 0;
                foreach (var p in dailyReportses)
                {
                    uint time = p.Ctm;
                    DateTime dateTime = ToDateTime(time);
                    double credit = p.Credit;
                    double equity = p.Equity;
                    double balance = p.Balance;

                    list.Add(new DailyReportFxtf(listLogin[i++],dateTime, credit, equity, balance));
                }
                dataGridView_DailyReports.DataSource = list;
                dataGridView_DailyReports.Visible = true;
            }
            else
            {
                MessageBox.Show(CONNECT_FIRST);
                dataGridView_DailyReports.DataSource = null;
            }
            ConnectToServer();
        }

        /// <summary>
        /// 
        /// </summary>
        class DailyReportFxtf
        {
            /// <summary>
            /// Login
            /// 
            /// </summary>
            public int Login { get; set; }

            /// <summary>
            /// Time
            /// 
            /// </summary>
            public DateTime Date { get; set; }

            /// <summary>
            /// Credit
            /// 
            /// </summary>
            public double Credit { get; set; }
            /// <summary>
            /// Equity
            /// 
            /// </summary>
            public double Equity { get; set; }
            /// <summary>
            /// Balance
            /// 
            /// </summary>
            public double Balance { get; set; }
            /// <summary>
            /// 
            /// </summary>
            /// <param name="_Login"></param>
            /// <param name="_dateTime"></param>
            /// <param name="_credit"></param>
            /// <param name="_equity"></param>
            /// <param name="_balance"></param>
            public DailyReportFxtf(int _Login,DateTime _dateTime, double _credit, double _equity, double _balance)
            {
                   Login = _Login;
                   Date = _dateTime;
                   Credit = _credit;
                   Equity = _equity;
                   Balance = _balance;
            }
        }
``

**Comment by Uriil** [comment]
You can not. In pumping mode only pumping methods are available.

**Comment by ranahamid** [comment]
Sir, Is there any way to get daily reports?

**Comment by Uriil** [comment]
You can get them without switching into pumping mode

**Comment by ranahamid** [comment]
Sir, After starting pumping mode, how can I stop it?

**Comment by Uriil** [comment]
There is no way to switch pumping off. You have to dispose wrapper and start new instance

**Comment by ranahamid** [comment]
Ok, Thank you.
