### ISSUE TITLE
CfgRequestCommon Convert null object

### ISSUE THREAD

**Issue by RayFungHK** [Uriil/MetaTrader4.Manager.Wrapper#64]
`Common config = metatrader.CfgRequestCommon();`

An unhandled exception of type 'System.NullReferenceException' occurred in P23.MetaTrader4.Manager.ClrWrapper.dll

So how can i fix it?

**Comment by Uriil** [comment]
Can you please provide me minimal example,  to reproduce this error?

**Comment by RayFungHK** [comment]
`
                metatrader.PumpingSwitchEx(PumpingMode.Default);
                metatrader.TradeAdded += (sender, record) =>
                {
                    TradeAddedPump(record);
                };
                metatrader.PumpingStarted += (sender, eventArgs) =>
                {
                    are.Set();
                };
                are.WaitOne();

                GetVersion();
                IList<UserRecord> users = metatrader.UsersRequest();
                while (true)
                {
                    string command = Console.ReadLine();
                }'
       ' static void GetVersion()
        {
            try
            {
                Common config = metatrader.CfgRequestCommon();
                Console.Read();
            }
            catch (Exception ex)
            {
                Console.Read();
            }
        }`

**Comment by Uriil** [comment]
You can not mix pumping and non pumping methods on same instance of wrapper. Thats internal restriction for MQ

**Comment by RayFungHK** [comment]
So how about ManagerCommon()? How can we use it?

**Comment by Uriil** [comment]
Before switching into pumping,like this:

    using(var mt = new ClrWrapper(...parameters...))
    {
        Common config = metatrader.CfgRequestCommon();
    }

**Comment by RayFungHK** [comment]
I get it now, before any pumping you can using non-pumping method, right?

**Comment by Uriil** [comment]
Yep, there is no way to mix. However nothing stops you from creating from creating two instances and use one of them in pumping and seconds in normal modes

**Comment by RayFungHK** [comment]
'An unhandled exception of type 'System.NullReferenceException' occurred in P23.MetaTrader4.Manager.ClrWrapper.dll

Additional information: Object reference not set to an instance of an object.'
Still throw exception

`               Common config = metatrader.CfgRequestCommon();

                metatrader.PumpingSwitchEx(PumpingMode.Default);
                metatrader.TradeAdded += (sender, record) =>
                {
                    TradeAddedPump(record);
                };
                metatrader.PumpingStarted += (sender, eventArgs) =>
                {
                    are.Set();
                };
                are.WaitOne();`

**Comment by Uriil** [comment]
You found a bug. Thank you for your feedback.

I just created new package and pushed it to nuget. I will appreciate if you check it and tell me if it's fixed or not.

Unfortunately I don't have admin access right now, so I can not check it on my own

**Comment by RayFungHK** [comment]
Thank You :D

**Comment by Uriil** [comment]
Did you have chance to test it?

**Comment by RayFungHK** [comment]
I'm taking full test for each function with MT4 Admin permission, but there are half of function (Update or Create new Record) was not work, maybe we can have skype text for deeply test
