### ISSUE TITLE
UserRequestNew could not create new user record

### ISSUE THREAD

**Issue by li0803** [Uriil/MetaTrader4.Manager.Wrapper#68]
i use this testing code to create a new user. but the result is 152 and the Login of userrecord is 0. seems that the user could not be created.
Can someone give some troubleshooting clue?
![qq 20160913221710](https://cloud.githubusercontent.com/assets/491759/18477806/863e780a-7a01-11e6-84c4-2693e3f9b5bb.jpg)

**Comment by Uriil** [comment]
You are mixing pumping and non pumping methods, which is not possible

**Comment by li0803** [comment]
Thanks Urill, your word helps me.

**Comment by li0803** [comment]
It is me again. Got 151 error when create a new trade, below are my test code:
`wrapper.PumpingSwitchEx(PumpingMode.Default);
                var addRecord = new TradeRecord();
                
                wrapper.TradeAdded += (sender, record) =>
                {
                    if (record.Login == signalAccount)
                    {
                        addRecord = record;
                        are.Set();
                    }
                };
                are.WaitOne();
                var newTrade = new TradeTransInfo();
                newTrade.Price = addRecord.OpenPrice;
                newTrade.Sl = addRecord.Sl;
                newTrade.Symbol = addRecord.Symbol;
                newTrade.Tp = addRecord.Tp;
                //newTrade.Type = TradeTransactionType.OrderReqOpen;
                newTrade.Volume = addRecord.Volume;
                newTrade.Cmd = addRecord.Cmd;
                //newTrade.Order = followAccount;
                newTrade.OrderBy = followAccount;
                result = wrapper.TradeTransaction(newTrade);
                Assert.IsTrue(result==0||result==1);`

do i mix pumping and non pumping mode again?

and, I still have some confuse on setting the property newTrade.Type, i take a look at the TradeTransactionType. My confuse is what are the difference between Instant Execution, Request Execution and Market Execution.
// Summary:
        //     Open order (Instant Execution)
        OrderIeOpen = 64,
        //
        // Summary:
        //     Open order (Request Execution)
        OrderReqOpen = 65,
        //
        // Summary:
        //     Open order (Market Execution)
        OrderMkOpen = 66,

Thanks.

**Comment by Uriil** [comment]
Yes, u mixing it again.

Regarding type, use only broker transactions(starts with Be)

**Comment by li0803** [comment]
can i switch back to request mode under extended pumping? I only find wrapper.DealerSwitch function that seems may help me and try it, but it give me "Callback handler alread allocated" exception.

I want to copy the trade which is received in TradeAdded event to another account. But the method to create new trade in extended pumping mode could be found. And under request mode, TradeAdded event does't work.

Thanks again

**Comment by Uriil** [comment]
You need to use separate connection

**Comment by li0803** [comment]
Thanks. It solve the problem
