### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by ObtGROUP** [Uriil/MetaTrader4.Manager.Wrapper#69]
My MetaTrader4 installed in "C:\Program Files(x86)\DestekFX\...." folder and its other files in "C:\Users\Baris\AppData\Roaming\MetaQuotes\Terminal\2C3166C170B721D9659DD6B07B90209E" folder.
My Visual Studio 2015 files in "C:\Baris\Forex\DestekFX\....." folder and its run perfectly. All DLLs is compiled and run perfectly.
mtmain.dlls in "C:\Baris\Forex\DLL\..." folder.
My real trade company's name is "DestekFX-Trade" shows in my metatrader4. (Not an IP adress and ports)
My login name is (for example) 123456.
my password is (for example) 123456789.

My code is there;
try
{
    var MT4 = new ClrWrapper(new ConnectionParameters {Server="DestekFX-Trade", Login=123456, Password="0123456789"}, @"C:\Baris\Forex\DLL\MT4\src\Libraries\mtmanapi\mtmanapi.dll");
   IList<UserRecord> users = MT4.UsersRequest();
   MessageBox.Show(users[0].Name);
}
catch (P23.MetaTrader4.Manager.Contracts.MetaTraderException E)
{
    MessageBox.Show(E.Message);
};
Then "Failed to connect to server" error.
Why?

**Comment by Uriil** [comment]
There is no dependency on mt4 terminal.
Do you have manager access to mt4 server?

**Comment by ObtGROUP** [comment]
I am sorry.
I use MetaTrader 4 (Build 1010) on DestekFX-Trade company real account.

**Comment by Uriil** [comment]
Sorry, but you won't be able to use it. It requires manager or admin access to server

**Comment by ObtGROUP** [comment]
OK. Thanks.
