### ISSUE TITLE
dll not load in windows server 2012

### ISSUE THREAD

**Issue by prodipgogoi** [Uriil/MetaTrader4.Manager.Wrapper#70]
I am having a problem "cannot load P23.MetaTrader4.Manager.ClrWrapper.dll" when i run my software in windows server 2012. but it is running in windows 10 desktop.

**Comment by Uriil** [comment]
I think you missing this dependency https://www.microsoft.com/en-us/download/details.aspx?id=48145 on server(version x86)

**Comment by prodipgogoi** [comment]
Thank you, it work fine now.
