### ISSUE TITLE
pumping timeout

### ISSUE THREAD

**Issue by li0803** [Uriil/MetaTrader4.Manager.Wrapper#71]
I have a timer to ping the manager server in very 10 seconds. But, occasionally, the I got the below error log:
2	2016.09.20 09:30:15.814	[ServerIP:Port]	[MyAccount]: pumping timeout: 12 seconds (Common error)
0	2016.09.20 09:30:15.814	[ServerIP:Port]	[MyAccount]: pumping mode stopped
And then, the wrapper class stop working but the ping time still works fine.

**Comment by Uriil** [comment]
I am not sure if you can use ping command in pumping mode and there is no reason to use it. Because there are dedicated event for pumping stopped and started
