### ISSUE TITLE
How can i get all trades history ? help me

### ISSUE THREAD

**Issue by tangfengray** [Uriil/MetaTrader4.Manager.Wrapper#72]
//my code
`
List< TradeRecord> tradesHisList = new List< TradeRecord>();
var users = ExtManager.UsersRequest();
int count = 0;

for (int i = 0; i < users.Count; i++)
 {
       if (users[i].Enable == 0) continue;
       var list = ExtManager.TradesUserHistory(users[i].Login, from.ToUnixTime(), to.ToUnixTime());
       tradesHisList.AddRange(list);
       count += list.Count;
}`

it runs 2 hours. is there any way to make it faster ?  help.

**Comment by Uriil** [comment]
You can use AdmTradesRequest, just place * for group parameter

**Comment by tangfengray** [comment]
thank u very much, i'll try it.
