### ISSUE TITLE
When will TradeDeleted event be triggered in pumping mode??

### ISSUE THREAD

**Issue by sysem85** [Uriil/MetaTrader4.Manager.Wrapper#74]
I tried no matter whether the trade is deleted through mt4 manager / mt4 client.

Only TradeClosed event would be triggered.

When will TradeDeleted event be triggered??

**Comment by Uriil** [comment]
It's only for pending trades

**Comment by sysem85** [comment]
is it only exist for pending limit order??

i have tried to delete the pending limit order from the client / manager, still only TradeClosed event would be triggered.

**Comment by Uriil** [comment]
Okay, I will need to check it, maybe something changed since I used it last time
