### ISSUE TITLE
IsConnected function 

### ISSUE THREAD

**Issue by sysem85** [Uriil/MetaTrader4.Manager.Wrapper#75]
When i connect to the MT4 server and idle for around 3 mins, the connection seems to be broken. (it return the NO_CONNECTION error code).

but when i check the connection at that time (using the IsConnected()), it returns true.

Is that a bug??

**Comment by Uriil** [comment]
I think u have to do some actions to keep connection alive. For example send ping command

**Comment by sysem85** [comment]
i can keep the connection alive by using the ping command in constant interval.

Just want to state that, we may not be able to check the connection by using IsConnected() function.

**Comment by Uriil** [comment]
But is it really valid?
