### ISSUE TITLE
OnlineUpdated Event

### ISSUE THREAD

**Issue by prodipgogoi** [Uriil/MetaTrader4.Manager.Wrapper#76]
What abjectly "OnlineUpdated" event as "onlineLogin" return? It is not the login as I checked. Does there any Pumping mode time out it it is then how to restart it?

**Comment by Uriil** [comment]
OnlineUpdated -> should be login, at least that's what they state in documentation
"Does there any Pumping mode time out it it is then how to restart it" - not really, but if connection gets interrupted, you will have to dispose client and create new one
