### ISSUE TITLE
Is there a way to be info when a new trade is about to add?

### ISSUE THREAD

**Issue by li0803** [Uriil/MetaTrader4.Manager.Wrapper#77]
Seems current code there is no such kind of event. I check the source code, is it possible to extend these code to added these kind of event.
`
case PUMP_UPDATE_TRADES:
			if (data != NULL)
			{
				TradeRecord *trade = (TradeRecord*)data;
				P23::MetaTrader4::Manager::Contracts::TradeRecord^ tradeRecordStruct = P23::MetaTrader4::Manager::ClrWrapper::Convert(trade);

				switch (type)
				{
					case TRANS_ADD:
						TradeAdded(this, tradeRecordStruct);
						break;
					case TRANS_DELETE:
						TradeClosed(this, tradeRecordStruct);
						break;
					case TRANS_UPDATE:
						if (trade->login == 0) 
							TradeDeleted(this, tradeRecordStruct);
						else
							TradeUpdated(this, tradeRecordStruct);
						break;
				}
			}
			break;
`

If it can be extended, What is the type for Trades Adding?

Thanks

**Comment by Uriil** [comment]
I am sorry, I did not get what is missing. Is not it code from file: https://github.com/Uriil/MetaTrader4.Manager.Wrapper/blob/master/src/P23.MetaTrader4.Manager.ClrWrapper/PumpingExtended.cpp

**Comment by li0803** [comment]
Sorry for my bad expression.

There is anything missing in code. It is the code from that file. I just want to know if it is possible to extend the code to raise the event of a new trade going to be added.

Currently, for my understand, all of trade's events are raised after the action on trade been performed. Is there any event that raise before a trade action performing.

**Comment by Uriil** [comment]
There is DealerMode, not sure if it exactly what you want, but there is no other way

**Comment by li0803** [comment]
I have a try with DealerMode.
newDealerManagerWrapper.DealerSwitch(DealerHandler);
-------------------------------------------------
public static void DealerHandler(int i)
        {
            Debug.WriteLine(i);
        }

My call back function is only called one time when my MT4 client is start up and the "i" parameter always is 0. I think I need to learn how to work with DealerMode. Are there sample code?

Or, my purpose is that I can be info when a new trade order is going to be added. Is there a workaround?

Thanks

**Comment by Uriil** [comment]
Not sure, you can try check metaquotes support site.

But basically, what you need(capture event before trade added) is done with Server API, not manager

**Comment by li0803** [comment]
OK. 

Thanks for your patient reply
