### ISSUE TITLE
SymbolsRefresh Usage

### ISSUE THREAD

**Issue by tamys** [Uriil/MetaTrader4.Manager.Wrapper#78]
Hi Urill,

Good Job.

I have an issue with the SymbolsRefresh method.

I'm using it in a web app, like following:

````
  using (var metatrader = new ClrWrapper(new ConnectionParameters
            {
                Login = 123456,
                Password = "managerPassword",
                Server = "123.123.123.123:443"
            }))
    {
       metatrader.SymbolsRefresh();
       return metatrader.SymbolGet("EURUSD");
    }
````

It executes correctly, but it then forces the asp net app pool to recycle. Is there any known issue on that, or any wrong in usage?

Even if i remove the SymbolGet() method and return null, it has the same effect.
SymbolGet() on its own without SymbolsRefresh before, it throws exception.

Thank in advance

**Comment by Uriil** [comment]
Pool recycle means that you have some unhandled exception.

Without knowing content of this exception I won't be able to help you.

But if you don't know, where to start, please check same code on console application

**Comment by tamys** [comment]
Yes I know that is due to unhandled exception, however the above method is in try-catch clause without any issue. I have also created the same scenario in console app by using your source code instead of nuget package. In console the problem is not visible, but in web app, it stacks the whole app until app pool restarts.

The only think i noticed is that: 'metatrader._callBackHandler.Target' threw an exception of type 'System.InvalidOperationException' - "Handle is not initialized." during ClrWrapper instantiation but again, this persists on other calls that do not end up with app pool restart. It happens just after symbolsrefresh

**Comment by Uriil** [comment]
> Handle is not initialized

This means that you using pumping methods without switching into pumping mode.

Maybe you can create minimal example and send it to me(attaach here zip package and I will review it)

**Comment by pantonis** [comment]
metatrader.SymbolGet("EURUSD"); is used on pumping. 
From the sample you are showing you aren't connected to pumping mode

**Comment by tamys** [comment]
Hi antonis,

I know that *get are for pumping. However my issue appears just after symbolsrefresh call. In other words, i have the same issue even if i remove the metatrader.SymbolGet("EURUSD"); line

**Comment by pantonis** [comment]
what is the result of the metatrader.SymbolsRefresh();

**Comment by pantonis** [comment]
if you remove  metatrader.SymbolGet("EURUSD"); it is impossible to get any exception. just tested it. So it means that you are doing something else later which is not in the snippet that you sent. Even if you provide wrong credentials you get MetaTraderException not an InvalidOperationException. Like Uriil said a small sample would be useful.

**Comment by tamys** [comment]
The code is used in a large web app, the symbolsrefresh causes the aspnet app pool to recycle. All clrwrapper initializations and usage are in try-catches clauses and everything else works great since now without any exceptions.

The problem is not visible in console app as there is no exception thrown. I suspect something in unmanaged code throws exception that causes the app pool to hang.

I ll try and provide a simple web api project to check if same is happened and come back soon.

**Comment by tamys** [comment]
> what is the result of the metatrader.SymbolsRefresh();

return is 0

**Comment by Uriil** [comment]
One idea. SymbolRefresh downloads some data from server and stores them next to mtmanapi.dll. Does your app pool has permissions to write to that folder?

**Comment by pantonis** [comment]
0 means that eveeyrhing is ok

**Comment by tamys** [comment]
> 0 means that everything is ok

Yes I know

> One idea. SymbolRefresh downloads some data from server and stores them next to mtmanapi.dll. Does your app pool has permissions to write to that folder?

next to mtmanapi.dll, symbols.raw, symgroups.raw, mailbox, news, logs were created just now, hence its not that either

also from logs everything seems ok:
0	2016.10.05 22:39:29.835		MetaTrader 4 Manager API build 830 initialized
0	2016.10.05 22:39:29.983	191.xxx.41.xxx:443	Connect
0	2016.10.05 22:39:30.190	191.xxx.41.xxx:443	'100': login (10.10)
0	2016.10.05 22:39:33.446	191.xxx.41.xxx:443	'100': refresh symbols
0	2016.10.05 22:39:34.904	191.xxx.41.xxx:443	'100': disconnect
0	2016.10.05 22:39:34.904		Remove: manager 29635AA0

**Comment by Uriil** [comment]
So we small example to reproduce this error...

**Comment by tamys** [comment]
> One idea. SymbolRefresh downloads some data from server and stores them next to mtmanapi.dll. Does your app pool has permissions to write to that folder?

Not exactly the permissions of folder was causing the issue, but the data dowloaded!!!
Changing a file in bin folder of webapp, forces recycle, therefore, after symbolsRefresh the symbols.raw changes, consequentially bin changes and app pool recycles:!~@
Just have to put all mtmanapi stuff in any place other than bin folder.

source: https://blogs.msdn.microsoft.com/tess/2006/08/02/asp-net-case-study-lost-session-variables-and-appdomain-recycles/  --- Unexpected config or bin directory changes

Confirmed by placing an empty txt file in bin/

Thanks @Uriil  @pantonis and keep great work.
