### ISSUE TITLE
MT5

### ISSUE THREAD

**Issue by pantonis** [Uriil/MetaTrader4.Manager.Wrapper#79]
Hi Uriil,

Do you have MT5 Manager Wrapper? I remember you had this repo in the past.

Thanks

**Comment by Uriil** [comment]
Yes, I have some drafts, but they are very old and I stopped developing it, because there is official one from metaquotes: https://support.metaquotes.net/en/docs/mt5/managerapi

**Comment by pantonis** [comment]
OK Thanks
