### ISSUE TITLE
What is the reason causing "pumping stop" event

### ISSUE THREAD

**Issue by li0803** [Uriil/MetaTrader4.Manager.Wrapper#81]
have anyone the experiment that why the pumping stop event is raised as there is no code to force to stop the clrwrapper or switch the mode?

**Comment by Uriil** [comment]
Most common one is connection problems.

However there are some other cases, for example invocation of nonpumping method in pumping mode

**Comment by li0803** [comment]
Thanks, seems connection problem has more possibility. My another Request mode wrapper encountered "Common Error" error at the same time.

And another question, some of my orders that open using manager wrapper can not close in MT4 terminal side in any way I can think out. The Journal gives me failed message "Trade is disabled".

2016.10.12 11:46:58.084	 order #3293701 buy 0.05 USDCHF closing at 0.00000 failed [Trade is disabled]
2016.10.12 11:46:57.922	 close order #3293701 buy 0.05 USDCHF at 0.97796 sl: 0.00000 tp: 0.00000 at price 0.00000
2016.10.12 11:46:46.681	 order #3496581 sell 0.01 USDCHF closing at 0.00000 failed [Trade is disabled]
2016.10.12 11:46:46.450	 close order #3496581 sell 0.01 USDCHF at 0.98865 sl: 0.00000 tp: 0.00000 at price 0.00000

Any troubleshoot suggestion?

Thanks very much.

**Comment by Uriil** [comment]
Is there something specific about those trades?

First at all, check if u can close such trade using MetaTrader Manager tool

**Comment by li0803** [comment]
Thanks, problem solved. Those orders can be closed using the Manager tool.

The order created by wrapper is a Dealer Mode ticket. Seems that dealer mode ticket can't close using terminal.
