### ISSUE TITLE
Profit always is 0 for orders which open and close using TradeTransaction function of wrapper API

### ISSUE THREAD

**Issue by li0803** [Uriil/MetaTrader4.Manager.Wrapper#83]
I use wrapper api to open and close order. But all of these orders display 0 in their Profit column in history.

However, I try with the Manager Tool to take the same operation on the same account, but this time, the Profit can have real lose or profit number.

Am I miss some parameter or setting?

Thanks

**Comment by Uriil** [comment]
Please provide code example, how u open and close trades

**Comment by li0803** [comment]
Sorry :(, please ignore my this question as I set the close price equal to open price when close those orders.
My bad coding skill.....

But I find out one interesting thing. The open and close price can be freely set when open or close a order using manager api. It can totally ignore the market price.
