### ISSUE TITLE
Pumping Stopped

### ISSUE THREAD

**Issue by mertoksuz** [Uriil/MetaTrader4.Manager.Wrapper#85]
hi, i'am using PumpingSwitch and getting SymbolInfoUpdated. Everything working fine for 3 hours. After 3 hours it is stopping. 

thank you.

**Comment by Uriil** [comment]
Hi, i don't think that its bug in wrapper. Just reconnect on such events

**Comment by mertoksuz** [comment]
Hi, thank you. Is there any simple way to reconnet in pumpingswicth mode ?? when it is stopped i can get that with notification codea.

**Comment by Uriil** [comment]
I was told, that u can call pumping switch again, after it stopped.

However, I was disposing client and creating new one

**Comment by mertoksuz** [comment]
hi, thank you again and one last question.

```
if ((PumpingNotificationCodes)i == PumpingNotificationCodes.Stop)
       {
             mt.Dispose();
             mt = new ClrWrapper(new ConnectionParameters { Login = XX, Password = "XX", Server = "XXXX" },
                @"mtmanapi.dll");

               ....... ( in here how can i stard pumping again ?? ))
        }
```

**Comment by Uriil** [comment]
Call PumpingSwitch method again

**Comment by mertoksuz** [comment]
thanks but this way i have to re-code pumpingswitch method each disconnect.

**Comment by Uriil** [comment]
Probably you can store pumping delegate in some property and field and reuse it? I don't understand where is your problem

**Comment by mertoksuz** [comment]
```
mt.PumpingSwitch(i =>
{
    if ((PumpingNotificationCodes)i == PumpingNotificationCodes.Stop)
    {

    }

    if ((PumpingNotificationCodes)i == PumpingNotificationCodes.BidAsk)
    {
        var symbols = mt.SymbolInfoUpdated();

        foreach (var item in symbols)
        {
               ......
        }
    }
 });
```

my problem is when it is stopped/disconnected, i have to reconnect to MT on each disconnect. how can define this reconnection process correctly.

thank you.

**Comment by mertoksuz** [comment]
hi, i handle it with timer thank you.

**Comment by Uriil** [comment]
It's really depends on your scenario
