### ISSUE TITLE
A question about pumping

### ISSUE THREAD

**Issue by tamys** [Uriil/MetaTrader4.Manager.Wrapper#87]
Hi @Uriil 

Lets say i have created a connection to mt4 and switched to pumping mode.

I used a pumping mode *Get and worked fine.

Then i need a *Request command and after that another *Get call.

Should i dispose the connection each time? 
Can i switch back to request mode?
Is request commands still work in pumping mode?
Should i have 2 Connections (1 *Request and 1 *Get) instead of connecting/disconnecting to server all time as the connection is costly?

What is the best practice according to your experience?

Thanks in advance

**Comment by Uriil** [comment]
Best way is to use two parallel connection s

**Comment by tamys** [comment]
Thanks a lot
