### ISSUE TITLE
Can I insert symbol to group symbol ? 

### ISSUE THREAD

**Issue by hisvarlar** [Uriil/MetaTrader4.Manager.Wrapper#88]
Hi,

I am trying add a symbol to group symbol. 

// mt pumping connection, mt2 is regular connection. 

**Group userGroup = mt.GroupRecordGet("testGroup"); // It works good.**

**userGroup.SecMargins[0].MarginDivider = 1;**
**userGroup.SecMargins[0].SwapLong = 1;**
**userGroup.SecMargins[0].SwapShort = 1;**
**userGroup.SecMargins[0].Symbol = "EURUSD";**

**mt2.CfgUpdateGroup(userGroup); // returns 0, ok.**

BUT I couldn't see inserted symbol on Administrator however when I trying check with API (**mt.GroupRecordGet("testGroup");** ) ,  **userGroup.SecMargins[0]** was filled.

API and Administrator panel show different results.

I restarted Server and Administrator panel after using **CfgUpdateGroup** function. But nothing was changed.

**Comment by hisvarlar** [comment]
If I insert a symbol from Administrator panel after this I can see that on API. And I can Update swap rates. But can't insert a new symbol.

**Comment by Uriil** [comment]
Hmm, not sure if I understand you correctly,

Can you provide me some screenshots from Mt Administrator, so I can understand exactly what you trying to do.

And one comment, not related to your bug: I would rather use CfgRequestGroup method, instead of pumping one, so you can avoid parallel connection(of course it might depends on your scenario and you might have a reason to do it your way)

**Comment by hisvarlar** [comment]
Mt administrator screenshot is below. I am trying add symbol by manager API.

![admin_grou](https://cloud.githubusercontent.com/assets/11486188/19926593/7bf960c2-a106-11e6-8014-cd4cba737a00.png)

**Comment by Uriil** [comment]
Thank you,

I will try to test it on my side today or tomorrow and will let you know

**Comment by hisvarlar** [comment]
Thanks, waiting for reply.

**Comment by Uriil** [comment]
You have to specify SecMarginsTotal as well

**Comment by hisvarlar** [comment]
Thanks a lot. It works.
