### ISSUE TITLE
UserRecordNew returns 3

### ISSUE THREAD

**Issue by sadro** [Uriil/MetaTrader4.Manager.Wrapper#91]
Hi,

I am trying to add new user to mt4 but UserRecordNew functions returns "3".
What is the meaning of "3"?

**Comment by Uriil** [comment]
Use errordescription method to get details

**Comment by sadro** [comment]
Thanks for you help.
"Invalid Parameters" is the exception.
But which parameters are missing how can i find it?
![ekran alintisi](https://cloud.githubusercontent.com/assets/7568182/20216336/04a05978-a82b-11e6-9b96-d1a1418d6786.JPG)

**Comment by Uriil** [comment]
Use different Password and Investor Password, confirm group name, that it
exists, and add number to all passwords

**Comment by sadro** [comment]
Thanks Urril.
Group name was the problem.

**Comment by pantonis** [comment]
@sadro You cannot set the Balance using UserRecordNew. UserRecord only gets balance. You have to create a balance transaction using TradeTransaction method.

**Comment by sadro** [comment]
@pantonis thanks for your response. 
I am trying to add balance to user but TradeTransaction method accept TradeTransactionInfo class. But this class has no LOGIN parameter accept. How can i add balance to LOGIN with this method?

**Comment by Uriil** [comment]
Please you property OrderBy for LOGIN

**Comment by sadro** [comment]
My Class is like this. But i am getting "Invalid Parameters" error.
![ekran alintisi](https://cloud.githubusercontent.com/assets/7568182/20378400/e348fa52-aca6-11e6-8e04-0dddf67f4d97.JPG)

**Comment by sadro** [comment]
@pantonis Thanks
