### ISSUE TITLE
Group Securities

### ISSUE THREAD

**Issue by sadro** [Uriil/MetaTrader4.Manager.Wrapper#92]
Hi,
I need to get the list of  (Group --> Securities) in Admin-Server side.
mt.GroupsRequest() function get all groups and details but i can't find the securities list.
In thew GroupSecurity list that is inside of Group Class there is no Enable-disable or something like this. I need group securities and all properties. Is there any way to get these?

![ekran alintisi](https://cloud.githubusercontent.com/assets/7568182/20535099/ad516216-b0f4-11e6-8ba3-2d319e9af0e1.JPG)

Thanks

**Comment by Uriil** [comment]
Method: CfgRequestGroup
Returned objects have property: ConGroupSec which contains securities

**Comment by sadro** [comment]
Hi Uriil,
CfgRequestGroup returns Group Class. In this class has secGroup IList. In this list i can find "Execution, Trade, Spread(SpreadDiff),Commission. But I cant find Type and IsEnabled. Which properties are them that i want?
Thanks
![ekran alintisi](https://cloud.githubusercontent.com/assets/7568182/20552059/f303532e-b157-11e6-8ea9-6cd5c092c6dd.JPG)

**Comment by sadro** [comment]
Thanks
