### ISSUE TITLE
unknown issue when getting userrecord

### ISSUE THREAD

**Issue by sysem85** [Uriil/MetaTrader4.Manager.Wrapper#93]
this error occurs from time to time.

but it is not repeatable with the same parameter after restarting the program.
=====================================================================
System.ArgumentException: The pointer passed in as a String must not be in the bottom 64K of the process's address space.
   at System.String..ctor(SByte* value)
   at P23.MetaTrader4.Manager.ClrWrapper.Convert(UserRecord* input)
   at P23.MetaTrader4.Manager.ClrWrapper.UserRecordsRequest(IList`1 logins)

**Comment by Uriil** [comment]
Without being able to reproduce it, I can not investigate it

**Comment by sysem85** [comment]
When I open the application for a while (10days)
Meanwhile,  I use ping() function to make sure the manager instance
connection.
After running the program for some period,  it would have this issue

**Comment by Uriil** [comment]
The only thing I can suggest is to refresh your connection few times a day

**Comment by sysem85** [comment]
I have the same idea to reclaim the connection in a constant interval.

Just see whether this workaround can solve this issue or not.
