### ISSUE TITLE
TradeTransaction not work while Credit In 

### ISSUE THREAD

**Issue by k7zj** [Uriil/MetaTrader4.Manager.Wrapper#96]
i met the same problem in [issures#41](https://github.com/Uriil/MetaTrader4.Manager.Wrapper/issues/41)

I set Expiration to different positive number , but it returns result=3 anyway.
Balance and withdrawal are working perfectly.

**Comment by Uriil** [comment]
You need to set Expiration to some time in future, ex today you can test with: 1481328000

**Comment by k7zj** [comment]
thx very much !!!!
it worked!
thank you.
