### ISSUE TITLE
'TradeClosed' event When a robot closes many trades at once

### ISSUE THREAD

**Issue by avibb** [Uriil/MetaTrader4.Manager.Wrapper#97]
hi,
I use the event "TradeClosed".
If the EA closes many trades at once, the event was missing some of the trades.
Is it possible ? or is it a mistake in my code? and what can be done for it?

Thank you 
(and sorry for my english)

**Comment by Uriil** [comment]
I am usually listen for trades from entire server and have not observe such behavior. However I assume that this bug is possible, but I don't have control over it, so won't be able to help you
